export type SROOffice = { en: string; ta: string };
export type SRODistrict = { en: string; ta: string; offices: SROOffice[] };
export type SROZone = { en: string; ta: string; districts: SRODistrict[] };

export const SRO_ZONES: SROZone[] = [
  {
    en: "Chennai Zone",
    ta: "சென்னை மண்டலம்",
    districts: [
      { en: "Chennai (North)", ta: "சென்னை (வடக்கு)", offices: [
        { en: "Sowcarpet", ta: "சவுக்கார்பேட்டை" },
        { en: "Royapuram", ta: "ராயபுரம்" },
        { en: "Tondiarpet", ta: "தொண்டியார்பேட்டை" },
        { en: "Tiruvottiyur", ta: "திருவொற்றியூர்" },
        { en: "Manali", ta: "மணலி" },
        { en: "Ennore", ta: "எண்ணூர்" },
        { en: "Madhavaram", ta: "மாதவரம்" },
        { en: "Perambur", ta: "பெரம்பூர்" },
        { en: "Ayanavaram", ta: "அயனாவரம்" },
        { en: "Villivakkam", ta: "வில்லிவாக்கம்" },
      ]},
      { en: "Chennai (Central)", ta: "சென்னை (மத்திய)", offices: [
        { en: "George Town", ta: "ஜார்ஜ் டவுன்" },
        { en: "Egmore", ta: "எழும்பூர்" },
        { en: "Triplicane", ta: "திருவல்லிக்கேணி" },
        { en: "Chetpet", ta: "சேட்பேட்டை" },
        { en: "Nungambakkam", ta: "நுங்கம்பாக்கம்" },
        { en: "Anna Nagar", ta: "அண்ணா நகர்" },
        { en: "Kilpauk", ta: "கில்பாக்" },
        { en: "Purasawalkam", ta: "புரசைவாக்கம்" },
        { en: "Vepery", ta: "வேப்பேரி" },
        { en: "Thousand Lights", ta: "ஆயிரம் விளக்கு" },
      ]},
      { en: "Chennai (South)", ta: "சென்னை (தெற்கு)", offices: [
        { en: "Mylapore", ta: "மயிலாப்பூர்" },
        { en: "T. Nagar", ta: "தி. நகர்" },
        { en: "Saidapet", ta: "சைதாப்பேட்டை" },
        { en: "Guindy", ta: "கிண்டி" },
        { en: "Adyar", ta: "அடையார்" },
        { en: "Velachery", ta: "வேளச்சேரி" },
        { en: "Tambaram", ta: "தாம்பரம்" },
        { en: "Pallavaram", ta: "பல்லாவரம்" },
        { en: "Sholinganallur", ta: "சோழிங்கநல்லூர்" },
        { en: "Neelankarai", ta: "நீலாங்கரை" },
        { en: "Madipakkam", ta: "மடிப்பாக்கம்" },
        { en: "Alandur", ta: "ஆலந்தூர்" },
      ]},
      { en: "Tiruvallur", ta: "திருவள்ளூர்", offices: [
        { en: "Tiruvallur", ta: "திருவள்ளூர்" },
        { en: "Poonamallee", ta: "பூந்தமல்லி" },
        { en: "Avadi", ta: "ஆவடி" },
        { en: "Ambattur", ta: "அம்பத்தூர்" },
        { en: "Tiruverkadu", ta: "திருவேற்காடு" },
        { en: "Ponneri", ta: "பொன்னேரி" },
        { en: "Gummidipoondi", ta: "கும்மிடிப்பூண்டி" },
        { en: "Uthukottai", ta: "உத்துக்கோட்டை" },
        { en: "Pallipattu", ta: "பல்லிபட்டு" },
        { en: "R.K. Pet", ta: "ஆர்.கே. பேட்டை" },
        { en: "Tiruttani", ta: "திருத்தணி" },
        { en: "Korattur", ta: "கொரட்டூர்" },
      ]},
      { en: "Kancheepuram", ta: "காஞ்சிபுரம்", offices: [
        { en: "Kancheepuram", ta: "காஞ்சிபுரம்" },
        { en: "Sriperumbudur", ta: "ஸ்ரீபெரும்புதூர்" },
        { en: "Walajabad", ta: "வாலாஜாபாத்" },
        { en: "Uthiramerur", ta: "உத்திரமேரூர்" },
        { en: "Kundrathur", ta: "குன்றத்தூர்" },
        { en: "Mangadu", ta: "மாங்காடு" },
        { en: "Chembarambakkam", ta: "செம்பரம்பாக்கம்" },
        { en: "Kanchipuram East", ta: "காஞ்சிபுரம் கிழக்கு" },
      ]},
      { en: "Chengalpattu", ta: "செங்கல்பட்டு", offices: [
        { en: "Chengalpattu", ta: "செங்கல்பட்டு" },
        { en: "Tirukalukundram", ta: "திருக்கழுக்குன்றம்" },
        { en: "Madurantakam", ta: "மதுராந்தகம்" },
        { en: "Cheyyur", ta: "செய்யூர்" },
        { en: "Tiruporur", ta: "திருப்போரூர்" },
        { en: "Vandalur", ta: "வண்டலூர்" },
        { en: "Mamallapuram", ta: "மாமல்லபுரம்" },
        { en: "Thiruvidanthai", ta: "திருவிடந்தை" },
        { en: "Padappai", ta: "படப்பை" },
        { en: "Thirukazhukundram", ta: "திருக்கழுக்குன்றம்" },
      ]},
    ],
  },
  {
    en: "Vellore Zone",
    ta: "வேலூர் மண்டலம்",
    districts: [
      { en: "Vellore", ta: "வேலூர்", offices: [
        { en: "Vellore", ta: "வேலூர்" },
        { en: "Katpadi", ta: "காட்பாடி" },
        { en: "Anaicut", ta: "ஆனைக்கட்டு" },
        { en: "K.V. Kuppam", ta: "கே.வி. குப்பம்" },
        { en: "Gudiyatham", ta: "குடியாத்தம்" },
        { en: "Pernambut", ta: "பேர்நாம்பட்டு" },
      ]},
      { en: "Ranipet", ta: "ராணிப்பேட்டை", offices: [
        { en: "Ranipet", ta: "ராணிப்பேட்டை" },
        { en: "Arcot", ta: "ஆற்காடு" },
        { en: "Walajah", ta: "வாலாஜா" },
        { en: "Sholinghur", ta: "சோழிங்கர்" },
        { en: "Arakkonam", ta: "அரக்கோணம்" },
        { en: "Nemili", ta: "நெமிலி" },
        { en: "Kaveripakkam", ta: "காவேரிப்பாக்கம்" },
      ]},
      { en: "Tirupathur", ta: "திருப்பத்தூர்", offices: [
        { en: "Tirupathur", ta: "திருப்பத்தூர்" },
        { en: "Vaniyambadi", ta: "வாணியம்பாடி" },
        { en: "Ambur", ta: "ஆம்பூர்" },
        { en: "Jolarpet", ta: "ஜோலார்பேட்டை" },
        { en: "Natrampalli", ta: "நாட்ரம்பள்ளி" },
        { en: "Alangayam", ta: "அலங்காயம்" },
        { en: "Kandili", ta: "கண்டிலி" },
      ]},
      { en: "Tiruvannamalai", ta: "திருவண்ணாமலை", offices: [
        { en: "Tiruvannamalai", ta: "திருவண்ணாமலை" },
        { en: "Polur", ta: "போளூர்" },
        { en: "Chengam", ta: "செங்கம்" },
        { en: "Kalasapakkam", ta: "களசபாக்கம்" },
        { en: "Chetpet", ta: "சேட்பேட்டை" },
        { en: "Arani", ta: "ஆரணி" },
        { en: "Cheyyar", ta: "செய்யாறு" },
        { en: "Vandavasi", ta: "வந்தவாசி" },
        { en: "Vembakkam", ta: "வேம்பாக்கம்" },
        { en: "Kilpennathur", ta: "கீழ்பெண்ணாத்தூர்" },
        { en: "Thandrampet", ta: "தண்டராம்பேட்" },
      ]},
      { en: "Krishnagiri", ta: "கிருஷ்ணகிரி", offices: [
        { en: "Krishnagiri", ta: "கிருஷ்ணகிரி" },
        { en: "Hosur", ta: "ஓசூர்" },
        { en: "Denkanikottai", ta: "தென்கனிக்கோட்டை" },
        { en: "Pochampalli", ta: "பொச்சம்பள்ளி" },
        { en: "Bargur", ta: "பர்கூர்" },
        { en: "Uthangarai", ta: "உத்தங்கரை" },
        { en: "Kelamangalam", ta: "கேளமங்கலம்" },
        { en: "Mathur", ta: "மாத்தூர்" },
        { en: "Anchetty", ta: "அஞ்செட்டி" },
      ]},
      { en: "Dharmapuri", ta: "தர்மபுரி", offices: [
        { en: "Dharmapuri", ta: "தர்மபுரி" },
        { en: "Palacode", ta: "பாலக்கோடு" },
        { en: "Pennagaram", ta: "பென்னாகரம்" },
        { en: "Harur", ta: "அரூர்" },
        { en: "Pappireddipatti", ta: "பாப்பிரெட்டிபட்டி" },
        { en: "Karimangalam", ta: "கரிமங்கலம்" },
        { en: "Nallampalli", ta: "நல்லம்பள்ளி" },
        { en: "Morappur", ta: "மொரப்பூர்" },
      ]},
    ],
  },
  {
    en: "Salem Zone",
    ta: "சேலம் மண்டலம்",
    districts: [
      { en: "Salem", ta: "சேலம்", offices: [
        { en: "Salem (Town)", ta: "சேலம் (நகரம்)" },
        { en: "Salem (Suburban)", ta: "சேலம் (புறநகர்)" },
        { en: "Shevapet", ta: "ஷேவாப்பேட்டை" },
        { en: "Ammapet", ta: "அம்மாப்பேட்டை" },
        { en: "Attur", ta: "அத்தூர்" },
        { en: "Yercaud", ta: "ஏற்காடு" },
        { en: "Mettur", ta: "மேட்டூர்" },
        { en: "Edappadi", ta: "எடப்பாடி" },
        { en: "Sankari", ta: "சங்கரி" },
        { en: "Omalur", ta: "ஓமலூர்" },
        { en: "Vazhapadi", ta: "வாழப்பாடி" },
        { en: "Gangavalli", ta: "கங்கவல்லி" },
        { en: "Pethanaickenpalayam", ta: "பேதநாயக்கன்பாளையம்" },
        { en: "Konganapuram", ta: "கொங்கணாபுரம்" },
        { en: "Thalaivasal", ta: "தலைவாசல்" },
      ]},
      { en: "Namakkal", ta: "நாமக்கல்", offices: [
        { en: "Namakkal", ta: "நாமக்கல்" },
        { en: "Rasipuram", ta: "ராசிபுரம்" },
        { en: "Tiruchengode", ta: "திருச்செங்கோடு" },
        { en: "Komarapalayam", ta: "கொமாரபாளையம்" },
        { en: "Paramathi", ta: "பரமத்தி" },
        { en: "Velur", ta: "வேலூர்" },
        { en: "Mohanur", ta: "மோகனூர்" },
        { en: "Sendamangalam", ta: "செந்தமங்கலம்" },
        { en: "Kolli Hills", ta: "கொல்லி மலை" },
        { en: "Kabilarmalai", ta: "கபிலர்மலை" },
        { en: "Erumapatty", ta: "எருமாப்பட்டி" },
        { en: "Pallipalayam", ta: "பள்ளிபாளையம்" },
        { en: "Elachipalayam", ta: "ஏலாச்சிபாளையம்" },
      ]},
      { en: "Erode", ta: "ஈரோடு", offices: [
        { en: "Erode (Town)", ta: "ஈரோடு (நகரம்)" },
        { en: "Erode (Suburban)", ta: "ஈரோடு (புறநகர்)" },
        { en: "Bhavani", ta: "பவானி" },
        { en: "Anthiyur", ta: "அந்தியூர்" },
        { en: "Gobichettipalayam", ta: "கோபிசெட்டிபாளையம்" },
        { en: "Sathyamangalam", ta: "சத்தியமங்கலம்" },
        { en: "Bhavanisagar", ta: "பவானிசாகர்" },
        { en: "Perundurai", ta: "பெருந்துறை" },
        { en: "Chennimalai", ta: "செண்ணிமலை" },
        { en: "Kodumudi", ta: "கொடுமுடி" },
        { en: "Modakurichi", ta: "மொடக்குறிச்சி" },
        { en: "Nambiyur", ta: "நம்பியூர்" },
        { en: "Talavadi", ta: "தளவாடி" },
      ]},
    ],
  },
  {
    en: "Coimbatore Zone",
    ta: "கோயம்புத்தூர் மண்டலம்",
    districts: [
      { en: "Coimbatore", ta: "கோயம்புத்தூர்", offices: [
        { en: "Coimbatore (Town)", ta: "கோயம்புத்தூர் (நகரம்)" },
        { en: "Coimbatore (North)", ta: "கோயம்புத்தூர் (வடக்கு)" },
        { en: "Coimbatore (South)", ta: "கோயம்புத்தூர் (தெற்கு)" },
        { en: "Peelamedu", ta: "பீளமேடு" },
        { en: "Singanallur", ta: "சிங்காநல்லூர்" },
        { en: "Saravanampatti", ta: "சரவணம்பட்டி" },
        { en: "Mettupalayam", ta: "மேட்டுப்பாளையம்" },
        { en: "Pollachi", ta: "பொள்ளாச்சி" },
        { en: "Valparai", ta: "வால்பாறை" },
        { en: "Anaimalai", ta: "ஆனைமலை" },
        { en: "Sulur", ta: "சூலூர்" },
        { en: "Annur", ta: "அன்னூர்" },
        { en: "Madukkarai", ta: "மதுக்கரை" },
        { en: "Karamadai", ta: "கரமடை" },
        { en: "Kinathukadavu", ta: "கிணத்துக்கடவு" },
      ]},
      { en: "Tiruppur", ta: "திருப்பூர்", offices: [
        { en: "Tiruppur (North)", ta: "திருப்பூர் (வடக்கு)" },
        { en: "Tiruppur (South)", ta: "திருப்பூர் (தெற்கு)" },
        { en: "Avinashi", ta: "அவிநாசி" },
        { en: "Palladam", ta: "பல்லடம்" },
        { en: "Udumalpet", ta: "உடுமலைப்பேட்டை" },
        { en: "Dharapuram", ta: "தாராபுரம்" },
        { en: "Kangeyam", ta: "காங்கேயம்" },
        { en: "Madathukulam", ta: "மடத்துக்குளம்" },
        { en: "Vellakoil", ta: "வெள்ளகோயில்" },
        { en: "Mulanur", ta: "முளனூர்" },
      ]},
      { en: "Nilgiris", ta: "நீலகிரி", offices: [
        { en: "Udhagamandalam", ta: "உதகமண்டலம்" },
        { en: "Coonoor", ta: "குன்னூர்" },
        { en: "Kotagiri", ta: "கோத்தகிரி" },
        { en: "Gudalur", ta: "குடலூர்" },
        { en: "Pandalur", ta: "பந்தலூர்" },
      ]},
    ],
  },
  {
    en: "Tiruchirapalli Zone",
    ta: "திருச்சிராப்பள்ளி மண்டலம்",
    districts: [
      { en: "Tiruchirapalli", ta: "திருச்சிராப்பள்ளி", offices: [
        { en: "Trichy (Town)", ta: "திருச்சி (நகரம்)" },
        { en: "Srirangam", ta: "ஸ்ரீரங்கம்" },
        { en: "Lalgudi", ta: "லால்குடி" },
        { en: "Manapparai", ta: "மணப்பாறை" },
        { en: "Musiri", ta: "முசிறி" },
        { en: "Thuraiyur", ta: "துறையூர்" },
        { en: "Tiruverumbur", ta: "திருவெறும்பூர்" },
        { en: "Manachanallur", ta: "மணச்சநல்லூர்" },
        { en: "Thottiyam", ta: "தோட்டியம்" },
        { en: "Thiruvaiyaru Road", ta: "திருவையாறு சாலை" },
        { en: "Tiruverumbur South", ta: "திருவெறும்பூர் தெற்கு" },
        { en: "Pullambadi", ta: "புள்ளம்பாடி" },
      ]},
      { en: "Karur", ta: "கரூர்", offices: [
        { en: "Karur", ta: "கரூர்" },
        { en: "Kulithalai", ta: "குளித்தலை" },
        { en: "Krishnarayapuram", ta: "கிருஷ்ணராயபுரம்" },
        { en: "Aravakurichi", ta: "அரவக்குறிச்சி" },
        { en: "Pugalur", ta: "புகலூர்" },
        { en: "Kadavur", ta: "காடவூர்" },
        { en: "Manmangalam", ta: "மான்மங்கலம்" },
      ]},
      { en: "Perambalur", ta: "பெரம்பலூர்", offices: [
        { en: "Perambalur", ta: "பெரம்பலூர்" },
        { en: "Veppanthattai", ta: "வெப்பந்தட்டை" },
        { en: "Kunnam", ta: "குன்னம்" },
        { en: "Alathur", ta: "அலத்தூர்" },
      ]},
      { en: "Ariyalur", ta: "அரியலூர்", offices: [
        { en: "Ariyalur", ta: "அரியலூர்" },
        { en: "Sendurai", ta: "செந்துரை" },
        { en: "Udayarpalayam", ta: "உதயார்பாளையம்" },
        { en: "Andimadam", ta: "ஆண்டிமடம்" },
        { en: "Jayankondam", ta: "ஜெயங்கொண்டம்" },
        { en: "T. Palur", ta: "டி. பாலூர்" },
      ]},
      { en: "Pudukkottai", ta: "புதுக்கோட்டை", offices: [
        { en: "Pudukkottai", ta: "புதுக்கோட்டை" },
        { en: "Aranthangi", ta: "அறந்தாங்கி" },
        { en: "Alangudi", ta: "அலங்குடி" },
        { en: "Avudaiyarkoil", ta: "ஆவுடையார்கோயில்" },
        { en: "Gandarvakottai", ta: "கந்தர்வக்கோட்டை" },
        { en: "Illupur", ta: "இலுப்பூர்" },
        { en: "Karambakudi", ta: "கரம்பக்குடி" },
        { en: "Kulathur", ta: "குலத்தூர்" },
        { en: "Manamelkudi", ta: "மணமேல்குடி" },
        { en: "Ponnamaravathi", ta: "பொன்னமராவதி" },
        { en: "Tirumayam", ta: "திருமயம்" },
        { en: "Viralimalai", ta: "விரளிமலை" },
      ]},
    ],
  },
  {
    en: "Thanjavur Zone",
    ta: "தஞ்சாவூர் மண்டலம்",
    districts: [
      { en: "Thanjavur", ta: "தஞ்சாவூர்", offices: [
        { en: "Thanjavur (Town)", ta: "தஞ்சாவூர் (நகரம்)" },
        { en: "Thanjavur (Suburban)", ta: "தஞ்சாவூர் (புறநகர்)" },
        { en: "Kumbakonam", ta: "கும்பகோணம்" },
        { en: "Papanasam", ta: "பாபநாசம்" },
        { en: "Pattukottai", ta: "பட்டுக்கோட்டை" },
        { en: "Peravurani", ta: "பேராவூரணி" },
        { en: "Orathanadu", ta: "ஓரத்தநாடு" },
        { en: "Thiruvaiyaru", ta: "திருவையாறு" },
        { en: "Thiruvonam", ta: "திருவோணம்" },
        { en: "Budalur", ta: "புதலூர்" },
        { en: "Madukkur", ta: "மடுக்கூர்" },
        { en: "Saliyamangalam", ta: "சாலியமங்கலம்" },
        { en: "Thiruvidaimaruthur", ta: "திருவிடைமருதூர்" },
      ]},
      { en: "Tiruvarur", ta: "திருவாரூர்", offices: [
        { en: "Tiruvarur", ta: "திருவாரூர்" },
        { en: "Mannargudi", ta: "மன்னார்குடி" },
        { en: "Needamangalam", ta: "நீடாமங்கலம்" },
        { en: "Nannilam", ta: "நன்னிலம்" },
        { en: "Thiruthuraipoondi", ta: "திருத்துறைப்பூண்டி" },
        { en: "Valangaiman", ta: "வாலங்கைமான்" },
        { en: "Koradacheri", ta: "கொரடசேரி" },
        { en: "Kodavasal", ta: "கோடவாசல்" },
        { en: "Muthupet", ta: "முத்துப்பேட்டை" },
      ]},
      { en: "Nagapattinam", ta: "நாகப்பட்டினம்", offices: [
        { en: "Nagapattinam", ta: "நாகப்பட்டினம்" },
        { en: "Kilvelur", ta: "கீழ்வேலூர்" },
        { en: "Vedaranyam", ta: "வேதாரண்யம்" },
        { en: "Thirukkuvalai", ta: "திருக்குவளை" },
      ]},
      { en: "Mayiladuthurai", ta: "மயிலாடுதுறை", offices: [
        { en: "Mayiladuthurai", ta: "மயிலாடுதுறை" },
        { en: "Sirkazhi", ta: "சீர்காழி" },
        { en: "Tharangambadi", ta: "தரங்கம்பாடி" },
        { en: "Kuthalam", ta: "குத்தாலம்" },
        { en: "Sembanarkoil", ta: "செம்பனார்கோயில்" },
      ]},
      { en: "Cuddalore", ta: "கடலூர்", offices: [
        { en: "Cuddalore (Town)", ta: "கடலூர் (நகரம்)" },
        { en: "Chidambaram", ta: "சிதம்பரம்" },
        { en: "Panruti", ta: "பண்ருட்டி" },
        { en: "Virudhachalam", ta: "விருத்தாசலம்" },
        { en: "Bhuvanagiri", ta: "புவனகிரி" },
        { en: "Kattumannarkoil", ta: "காட்டுமன்னார்கோயில்" },
        { en: "Kurinjipadi", ta: "குறிஞ்சிப்பாடி" },
        { en: "Tittakudi", ta: "திட்டகுடி" },
        { en: "Neyveli", ta: "நெய்வேலி" },
        { en: "Annagramam", ta: "அன்னகிராமம்" },
      ]},
      { en: "Villupuram", ta: "விழுப்புரம்", offices: [
        { en: "Villupuram", ta: "விழுப்புரம்" },
        { en: "Tindivanam", ta: "திண்டிவனம்" },
        { en: "Vanur", ta: "வானூர்" },
        { en: "Marakkanam", ta: "மரக்காணம்" },
        { en: "Vikravandi", ta: "விக்கிரவாண்டி" },
        { en: "Kandachipuram", ta: "காந்தாச்சிபுரம்" },
        { en: "Thirukoilur", ta: "திருக்கோயிலூர்" },
        { en: "Ulundurpet", ta: "உளுந்தூர்பேட்டை" },
        { en: "Sankarapuram", ta: "சங்கராபுரம்" },
        { en: "Gingee", ta: "செஞ்சி" },
        { en: "Mailam", ta: "மயிலம்" },
      ]},
      { en: "Kallakurichi", ta: "கள்ளக்குறிச்சி", offices: [
        { en: "Kallakurichi", ta: "கள்ளக்குறிச்சி" },
        { en: "Chinnasalem", ta: "சின்னசேலம்" },
        { en: "Tirukoilur", ta: "திருக்கோயிலூர்" },
        { en: "Sankarapuram", ta: "சங்கராபுரம்" },
        { en: "Kalvarayan Hills", ta: "கல்வராயன் மலை" },
        { en: "Rishivandiyam", ta: "ரிஷிவந்தியம்" },
        { en: "Thiyagadurgam", ta: "தியாகதுர்க்கம்" },
      ]},
    ],
  },
  {
    en: "Madurai Zone",
    ta: "மதுரை மண்டலம்",
    districts: [
      { en: "Madurai", ta: "மதுரை", offices: [
        { en: "Madurai (North)", ta: "மதுரை (வடக்கு)" },
        { en: "Madurai (South)", ta: "மதுரை (தெற்கு)" },
        { en: "Madurai East", ta: "மதுரை கிழக்கு" },
        { en: "Madurai West", ta: "மதுரை மேற்கு" },
        { en: "Anna Nagar (Madurai)", ta: "அண்ணா நகர் (மதுரை)" },
        { en: "Tirumangalam", ta: "திருமங்கலம்" },
        { en: "Usilampatti", ta: "உசிலம்பட்டி" },
        { en: "Peraiyur", ta: "பெரையூர்" },
        { en: "Melur", ta: "மேலூர்" },
        { en: "Vadipatti", ta: "வாடிப்பட்டி" },
        { en: "Sholavandan", ta: "சோழவந்தான்" },
        { en: "Thirupparankundram", ta: "திருப்பரங்குன்றம்" },
        { en: "Kalligudi", ta: "கல்லிக்குடி" },
        { en: "Alanganallur", ta: "அலங்காநல்லூர்" },
      ]},
      { en: "Theni", ta: "தேனி", offices: [
        { en: "Theni", ta: "தேனி" },
        { en: "Periyakulam", ta: "பெரியகுளம்" },
        { en: "Bodinayakanur", ta: "போடிநாயக்கனூர்" },
        { en: "Cumbum", ta: "கம்பம்" },
        { en: "Uthamapalayam", ta: "உத்தமபாளையம்" },
        { en: "Andipatti", ta: "ஆண்டிபட்டி" },
        { en: "Aundipatti", ta: "ஔண்டிபட்டி" },
      ]},
      { en: "Dindigul", ta: "திண்டுக்கல்", offices: [
        { en: "Dindigul (Town)", ta: "திண்டுக்கல் (நகரம்)" },
        { en: "Dindigul (Rural)", ta: "திண்டுக்கல் (கிராமம்)" },
        { en: "Palani", ta: "பழனி" },
        { en: "Oddanchatram", ta: "ஒட்டன்சத்திரம்" },
        { en: "Nilakottai", ta: "நிலக்கோட்டை" },
        { en: "Natham", ta: "நத்தம்" },
        { en: "Vedasandur", ta: "வேடசந்தூர்" },
        { en: "Kodaikanal", ta: "கொடைக்கானல்" },
        { en: "Athoor", ta: "ஆத்தூர்" },
        { en: "Gujiliamparai", ta: "குஜிலியம்பாறை" },
        { en: "Reddiarchatram", ta: "ரெட்டியார்சத்திரம்" },
        { en: "Shanarpatti", ta: "சாணார்பட்டி" },
        { en: "Thoppampatti", ta: "தோப்பம்பட்டி" },
      ]},
      { en: "Sivaganga", ta: "சிவகங்கை", offices: [
        { en: "Sivaganga", ta: "சிவகங்கை" },
        { en: "Karaikudi", ta: "காரைக்குடி" },
        { en: "Devakottai", ta: "தேவகோட்டை" },
        { en: "Manamadurai", ta: "மானாமதுரை" },
        { en: "Tirupathur", ta: "திருப்பத்தூர்" },
        { en: "Singampunari", ta: "சிங்கம்புணரி" },
        { en: "Ilayangudi", ta: "இளையங்குடி" },
        { en: "Kalayarkoil", ta: "காளையார்கோயில்" },
        { en: "Thiruppuvanam", ta: "திருப்புவனம்" },
        { en: "Kannangudi", ta: "கண்ணங்குடி" },
      ]},
      { en: "Ramanathapuram", ta: "ராமநாதபுரம்", offices: [
        { en: "Ramanathapuram", ta: "ராமநாதபுரம்" },
        { en: "Paramakudi", ta: "பரமக்குடி" },
        { en: "Rameswaram", ta: "ராமேஸ்வரம்" },
        { en: "Mudukulathur", ta: "முதுகுளத்தூர்" },
        { en: "Kamuthi", ta: "காமுதி" },
        { en: "Kadaladi", ta: "கடலாடி" },
        { en: "Tiruvadanai", ta: "திருவாடானை" },
        { en: "Mandapam", ta: "மண்டபம்" },
        { en: "R.S. Mangalam", ta: "ஆர்.எஸ். மங்கலம்" },
      ]},
      { en: "Virudhunagar", ta: "விருதுநகர்", offices: [
        { en: "Virudhunagar", ta: "விருதுநகர்" },
        { en: "Sivakasi", ta: "சிவகாசி" },
        { en: "Aruppukkottai", ta: "அருப்புக்கோட்டை" },
        { en: "Rajapalayam", ta: "ராஜபாளையம்" },
        { en: "Srivilliputhur", ta: "ஸ்ரீவில்லிபுத்தூர்" },
        { en: "Sattur", ta: "சாத்தூர்" },
        { en: "Tiruchuli", ta: "திருச்சுழி" },
        { en: "Watrap", ta: "வாத்ராப்" },
        { en: "Kariyapatti", ta: "காரியாபட்டி" },
        { en: "Narikudi", ta: "நரிக்குடி" },
      ]},
    ],
  },
  {
    en: "Tirunelveli Zone",
    ta: "திருநெல்வேலி மண்டலம்",
    districts: [
      { en: "Tirunelveli", ta: "திருநெல்வேலி", offices: [
        { en: "Tirunelveli (Town)", ta: "திருநெல்வேலி (நகரம்)" },
        { en: "Palayamkottai", ta: "பாளையங்கோட்டை" },
        { en: "Cheranmahadevi", ta: "சேரன்மகாதேவி" },
        { en: "Ambasamudram", ta: "அம்பாசமுத்திரம்" },
        { en: "Nanguneri", ta: "நாங்குநேரி" },
        { en: "Radhapuram", ta: "ராதாபுரம்" },
        { en: "Manur", ta: "மானூர்" },
        { en: "Sankarankoil", ta: "சங்கரன்கோயில்" },
        { en: "Vasudevanallur", ta: "வாசுதேவநல்லூர்" },
        { en: "Kadayanallur", ta: "கடையநல்லூர்" },
        { en: "Pavoorchatram", ta: "பவூர்சத்திரம்" },
      ]},
      { en: "Tenkasi", ta: "தென்காசி", offices: [
        { en: "Tenkasi", ta: "தென்காசி" },
        { en: "Shenkottai", ta: "செங்கோட்டை" },
        { en: "Kadayanallur", ta: "கடையநல்லூர்" },
        { en: "Sankarankoil", ta: "சங்கரன்கோயில்" },
        { en: "Alangulam", ta: "ஆலங்குளம்" },
        { en: "Veerakeralampudur", ta: "வீரகேரளம்புதூர்" },
        { en: "Kuruvikulam", ta: "குருவிக்குளம்" },
        { en: "Surandai", ta: "சுரண்டை" },
      ]},
      { en: "Thoothukudi", ta: "தூத்துக்குடி", offices: [
        { en: "Thoothukudi (Town)", ta: "தூத்துக்குடி (நகரம்)" },
        { en: "Thoothukudi (Rural)", ta: "தூத்துக்குடி (கிராமம்)" },
        { en: "Kovilpatti", ta: "கோவில்பட்டி" },
        { en: "Ettayapuram", ta: "எட்டயபுரம்" },
        { en: "Vilathikulam", ta: "விளாத்திக்குளம்" },
        { en: "Tiruchendur", ta: "திருச்செந்தூர்" },
        { en: "Srivaikuntam", ta: "ஸ்ரீவைகுண்டம்" },
        { en: "Sathankulam", ta: "சாத்தான்குளம்" },
        { en: "Ottapidaram", ta: "ஒட்டப்பிடாரம்" },
        { en: "Kayathar", ta: "காயத்தார்" },
        { en: "Pudur", ta: "புதூர்" },
      ]},
      { en: "Kanyakumari", ta: "கன்னியாகுமரி", offices: [
        { en: "Nagercoil", ta: "நாகர்கோயில்" },
        { en: "Kanyakumari", ta: "கன்னியாகுமரி" },
        { en: "Colachel", ta: "கொல்லச்சல்" },
        { en: "Thuckalay", ta: "துக்கலே" },
        { en: "Marthandam", ta: "மார்த்தாண்டம்" },
        { en: "Kuzhithurai", ta: "குழித்துறை" },
        { en: "Padmanabhapuram", ta: "பத்மநாபபுரம்" },
        { en: "Killiyoor", ta: "கிள்ளியூர்" },
        { en: "Boothapandi", ta: "பூதப்பாண்டி" },
        { en: "Munchirai", ta: "முஞ்சிறை" },
        { en: "Vilavancode", ta: "விளவங்கோடு" },
      ]},
    ],
  },
];
