// Tamil Nadu Sub-Registrar Office (SRO) hierarchy — sourced from
  // tnreginet.gov.in (Tamil Nadu Registration Department), mirrored via
  // proquiro.com/sro-directory/tamil-nadu (verified 2026-05-25).
  // Structure: 11 Registration Zones → ~38 revenue districts → 592 SROs.
  // SRO names taken from the official TNREGINET directory. For exact jurisdiction
  // (street/village level), check "Know Your Jurisdiction" on tnreginet.gov.in.

  export type SROOffice = { en: string; ta: string };
  export type SRODistrict = { en: string; ta: string; offices: SROOffice[] };
  export type SROZone = { en: string; ta: string; districts: SRODistrict[] };

  export const SRO_ZONES: SROZone[] = [
    {
    en: "Chennai Zone", ta: "சென்னை மண்டலம்",
    districts: [
      { en: "Chennai", ta: "சென்னை", offices: [
        { en: "Chennai Central Joint I", ta: "சென்னை மத்திய கூட்டு I" },
        { en: "Chennai Central Joint II", ta: "சென்னை மத்திய கூட்டு II" },
        { en: "Chennai North Joint I", ta: "சென்னை வடக்கு கூட்டு I" },
        { en: "Chennai South Joint I", ta: "சென்னை தெற்கு கூட்டு I" },
        { en: "Chennai South Joint II", ta: "சென்னை தெற்கு கூட்டு II" },
        { en: "Adayar", ta: "அடையார்" },
        { en: "Alandur", ta: "ஆலந்தூர்" },
        { en: "Ambattur", ta: "அம்பத்தூர்" },
        { en: "Anna Nagar", ta: "அண்ணா நகர்" },
        { en: "Ashok Nagar", ta: "அசோக் நகர்" },
        { en: "Avadi", ta: "ஆவடி" },
        { en: "Kodambakkam", ta: "கோடம்பாக்கம்" },
        { en: "Konnur", ta: "கொன்னூர்" },
        { en: "Kunrathur", ta: "குன்றத்தூர்" },
        { en: "Madhavaram", ta: "மாதவரம்" },
        { en: "Mylapore", ta: "மயிலாப்பூர்" },
        { en: "Neelankarai", ta: "நீலாங்கரை" },
        { en: "Padappai", ta: "படப்பை" },
        { en: "Periamet", ta: "பெரியமேடு" },
        { en: "Poonamallee", ta: "பூந்தமல்லி" },
        { en: "Purasaivakkam", ta: "புரசைவாக்கம்" },
        { en: "Ramakrishna Rajupettai", ta: "ராமகிருஷ்ண ராஜுபேட்டை" },
        { en: "Redhills", ta: "ரெட்ஹில்ஸ்" },
        { en: "Royapuram", ta: "ராயபுரம்" },
        { en: "Sembiam", ta: "செம்பியம்" },
        { en: "Sowcarpet", ta: "சவுகார்பேட்டை" },
        { en: "Thiruvottiyur", ta: "திருவொற்றியூர்" },
        { en: "Thiyagaraya Nagar", ta: "தியாகராய நகர்" },
        { en: "Triplicane", ta: "திருவல்லிக்கேணி" },
        { en: "Velacheri", ta: "வேளச்சேரி" },
        { en: "Villivakkam", ta: "வில்லிவாக்கம்" },
        { en: "Virugambakkam", ta: "விருகம்பாக்கம்" },
      ]},
      { en: "Tiruvallur", ta: "திருவள்ளூர்", offices: [
        { en: "Tiruvallur Joint I", ta: "திருவள்ளூர் கூட்டு I" },
        { en: "Tiruvallur Joint II", ta: "திருவள்ளூர் கூட்டு II" },
        { en: "Arani (Tiruvallur)", ta: "ஆரணி (திருவள்ளூர்)" },
        { en: "Gummidipoondi", ta: "கும்மிடிப்பூண்டி" },
        { en: "Manavalanagar", ta: "மணவாள நகர்" },
        { en: "Oothukkottai", ta: "உத்துக்கோட்டை" },
        { en: "Pallipattu", ta: "பல்லிபட்டு" },
        { en: "Perambakkam", ta: "பெரம்பாக்கம்" },
        { en: "Ponneri", ta: "பொன்னேரி" },
        { en: "Thiruttani", ta: "திருத்தணி" },
        { en: "Thiruvalankadu", ta: "திருவாலங்காடு" },
      ]},
    ],
  },
  {
    en: "Chengalpattu Zone", ta: "செங்கல்பட்டு மண்டலம்",
    districts: [
      { en: "Chengalpattu", ta: "செங்கல்பட்டு", offices: [
        { en: "Chengleput Joint I", ta: "செங்கல்பட்டு கூட்டு I" },
        { en: "Chengleput Joint II", ta: "செங்கல்பட்டு கூட்டு II" },
        { en: "Acchirapakkam", ta: "அச்சிறுப்பாக்கம்" },
        { en: "Cheyyur", ta: "செய்யூர்" },
        { en: "Gooduvancheri", ta: "குடுவாஞ்சேரி" },
        { en: "Kelampakkam", ta: "கேளம்பாக்கம்" },
        { en: "Madurandakam", ta: "மதுராந்தகம்" },
        { en: "Navalur", ta: "நாவலூர்" },
        { en: "Pallavaram", ta: "பல்லாவரம்" },
        { en: "Pammal", ta: "பம்மல்" },
        { en: "Selaiyur", ta: "செலையூர்" },
        { en: "Tambaram Joint I", ta: "தாம்பரம் கூட்டு I" },
        { en: "Thirukazhukundram", ta: "திருக்கழுக்குன்றம்" },
        { en: "Thiruporur", ta: "திருப்போரூர்" },
        { en: "Vandaloor", ta: "வண்டலூர்" },
      ]},
      { en: "Kancheepuram", ta: "காஞ்சிபுரம்", offices: [
        { en: "Kanchipuram Joint I", ta: "காஞ்சிபுரம் கூட்டு I" },
        { en: "Kanchipuram Joint II", ta: "காஞ்சிபுரம் கூட்டு II" },
        { en: "Kanchipuram Joint IV", ta: "காஞ்சிபுரம் கூட்டு IV" },
        { en: "Salavakkam", ta: "சலவாக்கம்" },
        { en: "Sriperumpudur", ta: "ஸ்ரீபெரும்புதூர்" },
        { en: "Sunguvarchattram", ta: "சுங்குவார்சத்திரம்" },
        { en: "Thamal", ta: "தாமல்" },
        { en: "Uthiramerur", ta: "உத்திரமேரூர்" },
        { en: "Walajabad", ta: "வாலாஜாபாத்" },
      ]},
    ],
  },
  {
    en: "Coimbatore Zone", ta: "கோயம்புத்தூர் மண்டலம்",
    districts: [
      { en: "Coimbatore", ta: "கோயம்புத்தூர்", offices: [
        { en: "Coimbatore North Joint I", ta: "கோயம்புத்தூர் வடக்கு கூட்டு I" },
        { en: "Coimbatore South Joint I", ta: "கோயம்புத்தூர் தெற்கு கூட்டு I" },
        { en: "Anaimalai", ta: "ஆனைமலை" },
        { en: "Annur", ta: "அன்னூர்" },
        { en: "Ganapathy", ta: "கணபதி" },
        { en: "Gandhipuram", ta: "காந்திபுரம்" },
        { en: "Gomangalam", ta: "கோமங்களம்" },
        { en: "Karumathampatti", ta: "கருமத்தம்பட்டி" },
        { en: "Kinathukkadavu", ta: "கிணத்துக்கடவு" },
        { en: "Madukkarai", ta: "மதுக்கரை" },
        { en: "Mettupalayam", ta: "மேட்டுப்பாளையம்" },
        { en: "Negamam", ta: "நேகமம்" },
        { en: "Peelamedu", ta: "பீளமேடு" },
        { en: "Periyanayakkan Palayam", ta: "பெரியநாயக்கன் பாளையம்" },
        { en: "Pollachi", ta: "பொள்ளாச்சி" },
        { en: "Pongalur", ta: "பொங்களூர்" },
        { en: "Sarkarsamakulam", ta: "சர்க்கார்சமாகுளம்" },
        { en: "Singanallur", ta: "சிங்காநல்லூர்" },
        { en: "Sulur", ta: "சூலூர்" },
        { en: "Thondamuthur", ta: "தொண்டாமுத்தூர்" },
        { en: "Thookanaicken Palayam", ta: "தூக்காநாயக்கன் பாளையம்" },
        { en: "Vadavalli", ta: "வடவல்லி" },
      ]},
      { en: "Tiruppur", ta: "திருப்பூர்", offices: [
        { en: "Tiruppur Joint I", ta: "திருப்பூர் கூட்டு I" },
        { en: "Tiruppur Joint II", ta: "திருப்பூர் கூட்டு II" },
        { en: "Avinasi", ta: "அவிநாசி" },
        { en: "Dharapuram", ta: "தாராபுரம்" },
        { en: "Kangeyam", ta: "காங்கேயம்" },
        { en: "Kaniyur", ta: "கனியூர்" },
        { en: "Kunnathur", ta: "குன்னத்தூர்" },
        { en: "Madathukulam", ta: "மடத்துக்குளம்" },
        { en: "Moolanur", ta: "மூலனூர்" },
        { en: "Nallur (Tiruppur)", ta: "நல்லூர் (திருப்பூர்)" },
        { en: "Palladam", ta: "பல்லடம்" },
        { en: "Udumalpettai", ta: "உடுமலைப்பேட்டை" },
        { en: "Uthukuli", ta: "உத்துக்குளி" },
        { en: "Vellakovil", ta: "வெள்ளக்கோயில்" },
      ]},
      { en: "Nilgiris", ta: "நீலகிரி", offices: [
        { en: "Uthagamandalam Joint I", ta: "உதகமண்டலம் கூட்டு I" },
        { en: "Uthagamandalam Joint II", ta: "உதகமண்டலம் கூட்டு II" },
        { en: "Coonoor (Uthagamandalam)", ta: "குன்னூர் (உதகமண்டலம்)" },
        { en: "Goodaloor", ta: "குடலூர்" },
        { en: "Kothagiri", ta: "கோத்தகிரி" },
      ]},
      { en: "Erode", ta: "ஈரோடு", offices: [
        { en: "Erode Joint I", ta: "ஈரோடு கூட்டு I" },
        { en: "Ammapettai (Erode)", ta: "அம்மாப்பேட்டை (ஈரோடு)" },
        { en: "Anthiyur", ta: "அந்தியூர்" },
        { en: "Avalpoondurai", ta: "அவல்பூந்துறை" },
        { en: "Bhavani", ta: "பவானி" },
        { en: "Chennimalai", ta: "செண்ணிமலை" },
        { en: "Gobichettipalayam Joint I", ta: "கோபிசெட்டிபாளையம் கூட்டு I" },
        { en: "Gobichettipalayam Joint II", ta: "கோபிசெட்டிபாளையம் கூட்டு II" },
        { en: "Kavundapadi", ta: "கவுண்டம்பாடி" },
        { en: "Kodumudi", ta: "கொடுமுடி" },
        { en: "Nambiyur", ta: "நம்பியூர்" },
        { en: "Perundurai", ta: "பெருந்துறை" },
        { en: "Punchaipuliyampatti", ta: "புஞ்சைபுளியம்பட்டி" },
        { en: "Sathyamangalam", ta: "சத்தியமங்கலம்" },
        { en: "Sivagiri (Erode)", ta: "சிவகிரி (ஈரோடு)" },
        { en: "Surampatti", ta: "சுராம்பட்டி" },
        { en: "Thalavadi", ta: "தளவாடி" },
        { en: "Thingalur", ta: "திங்களூர்" },
        { en: "Thottipalayam", ta: "தோட்டிபாளையம்" },
      ]},
    ],
  },
  {
    en: "Cuddalore Zone", ta: "கடலூர் மண்டலம்",
    districts: [
      { en: "Cuddalore", ta: "கடலூர்", offices: [
        { en: "Cuddalore Joint I", ta: "கடலூர் கூட்டு I" },
        { en: "Cuddalore Joint II", ta: "கடலூர் கூட்டு II" },
        { en: "Chidambaram Joint I", ta: "சிதம்பரம் கூட்டு I" },
        { en: "Annagramam", ta: "அன்னகிராமம்" },
        { en: "Bhuvanagiri", ta: "புவனகிரி" },
        { en: "Kammapuram", ta: "காமாபுரம்" },
        { en: "Kullanchavadi", ta: "குள்ளஞ்சாவடி" },
        { en: "Kumarachi", ta: "குமாரச்சி" },
        { en: "Kurinjipadi", ta: "குறிஞ்சிப்பாடி" },
        { en: "Nellikuppam", ta: "நெல்லிக்குப்பம்" },
        { en: "Panruti", ta: "பண்ருட்டி" },
        { en: "Parangipettai", ta: "பரங்கிப்பேட்டை" },
        { en: "Puduchattiram (Chidambaram)", ta: "புதுசத்திரம் (சிதம்பரம்)" },
        { en: "Sethiyathope", ta: "செத்தியாதோப்பு" },
        { en: "Sirupakkam", ta: "சிறுபாக்கம்" },
        { en: "Thittakudi", ta: "திட்டகுடி" },
        { en: "Vadalur", ta: "வடலூர்" },
        { en: "Virudhachalam Joint I", ta: "விருத்தாசலம் கூட்டு I" },
        { en: "Nallur (Virudhachalam)", ta: "நல்லூர் (விருத்தாசலம்)" },
        { en: "Veppur (Virudhachalam)", ta: "வெப்பூர் (விருத்தாசலம்)" },
        { en: "Pennadam", ta: "பென்னாடம்" },
      ]},
      { en: "Villupuram", ta: "விழுப்புரம்", offices: [
        { en: "Villupuram Joint I", ta: "விழுப்புரம் கூட்டு I" },
        { en: "Villupuram Joint II", ta: "விழுப்புரம் கூட்டு II" },
        { en: "Tindivanam Joint I", ta: "திண்டிவனம் கூட்டு I" },
        { en: "Tindivanam Joint II", ta: "திண்டிவனம் கூட்டு II" },
        { en: "Aragandanallur", ta: "ஆரகண்டநல்லூர்" },
        { en: "Avalurpettai", ta: "ஆவலூர்பேட்டை" },
        { en: "Avarapakkam", ta: "ஆவரப்பாக்கம்" },
        { en: "Gingee", ta: "செஞ்சி" },
        { en: "Kadampuliyur", ta: "கடம்புலியூர்" },
        { en: "Kandamangalam", ta: "காந்தமங்கலம்" },
        { en: "Mailam", ta: "மயிலம்" },
        { en: "Marakkanam", ta: "மரக்காணம்" },
        { en: "Mangalampettai", ta: "மங்களம்பேட்டை" },
        { en: "Pudupettai", ta: "புதுப்பேட்டை" },
        { en: "Sathyamangalam (Tindivanam)", ta: "சத்தியமங்கலம் (திண்டிவனம்)" },
        { en: "Thirunavalur", ta: "திருநாவலூர்" },
        { en: "Thiruvennainallur", ta: "திருவெண்ணைநல்லூர்" },
        { en: "Thozhudur", ta: "தோழுதூர்" },
        { en: "Valathi", ta: "வளத்தி" },
        { en: "Valavanur", ta: "வழவனூர்" },
        { en: "Vallam (Tindivanam)", ta: "வல்லம் (திண்டிவனம்)" },
        { en: "Vanapuram", ta: "வனபுரம்" },
        { en: "Vanur", ta: "வானூர்" },
        { en: "Vikkravandi", ta: "விக்கிரவாண்டி" },
      ]},
      { en: "Kallakurichi", ta: "கள்ளக்குறிச்சி", offices: [
        { en: "Kallakurichi Joint I", ta: "கள்ளக்குறிச்சி கூட்டு I" },
        { en: "Kallakurichi Joint II", ta: "கள்ளக்குறிச்சி கூட்டு II" },
        { en: "Ananthapuram", ta: "ஆனந்தபுரம்" },
        { en: "Anniyur", ta: "அன்னியூர்" },
        { en: "Chinna Salem", ta: "சின்னசேலம்" },
        { en: "Elavanasur", ta: "எளவாநசூர்" },
        { en: "Manalurpettai", ta: "மணலூர்பேட்டை" },
        { en: "Nagalur", ta: "நாகலூர்" },
        { en: "Rishivanthiyam", ta: "ரிஷிவந்தியம்" },
        { en: "Sankarapuram", ta: "சங்கராபுரம்" },
        { en: "Thirukoilur", ta: "திருக்கோயிலூர்" },
        { en: "Thirumuttam", ta: "திருமுட்டம்" },
        { en: "Thiyagadurgam", ta: "தியாகதுர்க்கம்" },
        { en: "Ulundurpettai", ta: "உளுந்தூர்பேட்டை" },
        { en: "Vadakkananthal", ta: "வடக்கானந்தல்" },
        { en: "Vadaponparappi", ta: "வடபொன்பறப்பி" },
      ]},
    ],
  },
  {
    en: "Madurai Zone", ta: "மதுரை மண்டலம்",
    districts: [
      { en: "Madurai", ta: "மதுரை", offices: [
        { en: "Madurai North Joint I", ta: "மதுரை வடக்கு கூட்டு I" },
        { en: "Madurai South Joint I", ta: "மதுரை தெற்கு கூட்டு I" },
        { en: "Madurai South Joint IV", ta: "மதுரை தெற்கு கூட்டு IV" },
        { en: "Alanganallur", ta: "அலங்காநல்லூர்" },
        { en: "Chekkanoorani", ta: "செக்கானூரணி" },
        { en: "Chellampatti", ta: "செல்லம்பட்டி" },
        { en: "Chettikulam (Madurai North)", ta: "செட்டிக்குளம் (மதுரை வடக்கு)" },
        { en: "Cholavanthan", ta: "சோழவந்தான்" },
        { en: "Karungalakkudi", ta: "கருங்களக்குடி" },
        { en: "Karuppayoorani", ta: "கருப்பாயூரணி" },
        { en: "Kallikudi", ta: "கல்லிக்குடி" },
        { en: "Melur (East)", ta: "மேலூர் (கிழக்கு)" },
        { en: "Melur (West)", ta: "மேலூர் (மேற்கு)" },
        { en: "Nagamalai Pudukottai", ta: "நாகமலை புதுக்கோட்டை" },
        { en: "Peraiyur", ta: "பெரையூர்" },
        { en: "Samanatham", ta: "சமனத்தம்" },
        { en: "Thirumangalam", ta: "திருமங்கலம்" },
        { en: "Thiruparankunram", ta: "திருப்பரங்குன்றம்" },
        { en: "Usilampatti", ta: "உசிலம்பட்டி" },
        { en: "Vada Madurai", ta: "வட மதுரை" },
        { en: "Vadipatti", ta: "வாடிப்பட்டி" },
        { en: "Vilangudi", ta: "விளங்குடி" },
      ]},
      { en: "Dindigul", ta: "திண்டுக்கல்", offices: [
        { en: "Dindigul Joint I", ta: "1 எண் இணை சார்பதிவாளர் திண்டுக்கல்" },
        { en: "Dindigul Joint II", ta: "2 எண் இணை சார்பதிவாளர் திண்டுக்கல்" },
        { en: "Aathur (Dindigul)", ta: "ஆத்தூர் (திண்டுக்கல்)" },
        { en: "Ayyampalayam", ta: "அய்யம்பாளையம்" },
        { en: "Chathirapatti", ta: "சத்திரப்பட்டி" },
        { en: "Chinnalapatti", ta: "சின்னாளப்பட்டி" },
        { en: "Ezhumalai", ta: "எழுமலை" },
        { en: "Kadamalaikundu", ta: "கடமலைக்குண்டு" },
        { en: "Kallimandayam", ta: "கல்லிமண்டயம்" },
        { en: "Kannivadi", ta: "கன்னிவாடி" },
        { en: "Kodaikkanal", ta: "கொடைக்கானல்" },
        { en: "Kujiliamparai", ta: "குஜிலியம்பாறை" },
        { en: "Natham", ta: "நத்தம்" },
        { en: "Nagal Nayakkampatti", ta: "நாகல் நாயக்கம்பட்டி" },
        { en: "Nilakkottai", ta: "நிலக்கோட்டை" },
        { en: "Ottanchathiram", ta: "ஒட்டன்சத்திரம்" },
        { en: "Palani Joint I", ta: "பழனி கூட்டு I" },
        { en: "Palani Joint II", ta: "பழனி கூட்டு II" },
        { en: "Sanarpatti", ta: "சானார்பட்டி" },
        { en: "Sendhurai (Dindigul)", ta: "செந்துறை (திண்டுக்கல்)" },
        { en: "Thamaraipatti", ta: "தாமரைப்பட்டி" },
        { en: "Vathalagundu", ta: "வாத்தலகுண்டு" },
        { en: "Veda Senthur", ta: "வேடசந்தூர்" },
      ]},
      { en: "Theni", ta: "தேனி", offices: [
        { en: "Theni", ta: "தேனி" },
        { en: "Andipatti", ta: "ஆண்டிபட்டி" },
        { en: "Bodinayakkanur", ta: "போடிநாயக்கனூர்" },
        { en: "Chinnamanur", ta: "சின்னமனூர்" },
        { en: "Cumbum", ta: "கம்பம்" },
        { en: "Kathakkinaru", ta: "காத்தக்கினாறு" },
        { en: "Keeranur", ta: "கீரனூர்" },
        { en: "Periyakulam Joint I", ta: "பெரியகுளம் கூட்டு I" },
        { en: "Periyakulam Joint II", ta: "பெரியகுளம் கூட்டு II" },
        { en: "Podumbu", ta: "பொடும்பு" },
        { en: "Thallakualam", ta: "தள்ளக்குளம்" },
        { en: "Thevaram", ta: "தேவாரம்" },
        { en: "Uthamapalayam", ta: "உத்தமபாளையம்" },
      ]},
    ],
  },
  {
    en: "Ramanathapuram Zone", ta: "ராமநாதபுரம் மண்டலம்",
    districts: [
      { en: "Ramanathapuram", ta: "ராமநாதபுரம்", offices: [
        { en: "Ramanathapuram Joint I", ta: "ராமநாதபுரம் கூட்டு I" },
        { en: "Ramanathapuram Joint II", ta: "ராமநாதபுரம் கூட்டு II" },
        { en: "Abiramam", ta: "அபிராமம்" },
        { en: "Boghalur", ta: "போகலூர்" },
        { en: "Kadaladi (Ramanathapuram)", ta: "கடலாடி (ராமநாதபுரம்)" },
        { en: "Kamudhi", ta: "காமுதி" },
        { en: "Keelakkarai", ta: "கீழக்கரை" },
        { en: "Meemisal", ta: "மீமிசல்" },
        { en: "Mudhukulathur", ta: "முதுகுளத்தூர்" },
        { en: "Nayinar Kovil", ta: "நயினார் கோயில்" },
        { en: "Panthalkudi", ta: "பந்தல்குடி" },
        { en: "Paramakudi", ta: "பரமக்குடி" },
        { en: "Rajasinga Mangalam", ta: "ராஜசிங்க மங்களம்" },
        { en: "Rameshwaram", ta: "ராமேஸ்வரம்" },
        { en: "Sayalkudi", ta: "சாயல்குடி" },
        { en: "Thiruvadanai", ta: "திருவாடானை" },
        { en: "Thondi", ta: "தொண்டி" },
        { en: "Velipattinam", ta: "வேலிப்பட்டினம்" },
      ]},
      { en: "Sivagangai", ta: "சிவகங்கை", offices: [
        { en: "Sivagangai Joint I", ta: "சிவகங்கை கூட்டு I" },
        { en: "Sivagangai Joint II", ta: "சிவகங்கை கூட்டு II" },
        { en: "Karaikudi Joint I", ta: "காரைக்குடி கூட்டு I" },
        { en: "Karaikudi Joint II", ta: "காரைக்குடி கூட்டு II" },
        { en: "Devakkottai", ta: "தேவகோட்டை" },
        { en: "Ilayangudi", ta: "இளையங்குடி" },
        { en: "Kalayarkoil", ta: "காளையார்கோயில்" },
        { en: "Madakkupatti", ta: "மடக்குப்பட்டி" },
        { en: "Manamadurai", ta: "மானாமதுரை" },
        { en: "Perunazhi", ta: "பெருநழி" },
        { en: "Ponnamaravathi", ta: "பொன்னமராவதி" },
        { en: "Singampunari", ta: "சிங்கம்புணரி" },
        { en: "Thiruppathur (Karaikudi)", ta: "திருப்பத்தூர் (காரைக்குடி)" },
        { en: "Thirupuvanam", ta: "திருப்புவனம்" },
      ]},
      { en: "Virudhunagar", ta: "விருதுநகர்", offices: [
        { en: "Virudhunagar Joint I", ta: "விருதுநகர் கூட்டு I" },
        { en: "Virudhunagar Joint II", ta: "விருதுநகர் கூட்டு II" },
        { en: "Aruppukkottai", ta: "அருப்புக்கோட்டை" },
        { en: "Kariapatti", ta: "காரியாபட்டி" },
        { en: "Keela Rajakularaman", ta: "கீழ ராஜகுலராமன்" },
        { en: "M. Rettiyapetty", ta: "ம. ரெட்டியப்பேட்டி" },
        { en: "Rajapalayam", ta: "ராஜபாளையம்" },
        { en: "Sathur", ta: "சாத்தூர்" },
        { en: "Sethur", ta: "சேதூர்" },
        { en: "Sivakasi", ta: "சிவகாசி" },
        { en: "Srivilliputhur", ta: "ஸ்ரீவில்லிபுத்தூர்" },
        { en: "Thiruchuli", ta: "திருச்சுழி" },
        { en: "Thiruthangal", ta: "திருத்தங்கல்" },
        { en: "Vathirairuppu", ta: "வாத்திரையிருப்பு" },
        { en: "Veerachozhan", ta: "வீரசோழன்" },
      ]},
    ],
  },
  {
    en: "Salem Zone", ta: "சேலம் மண்டலம்",
    districts: [
      { en: "Salem", ta: "சேலம்", offices: [
        { en: "Salem East Joint I", ta: "சேலம் கிழக்கு கூட்டு I" },
        { en: "Salem West Joint I", ta: "சேலம் மேற்கு கூட்டு I" },
        { en: "Salem West Joint III", ta: "சேலம் மேற்கு கூட்டு III" },
        { en: "Aathur (Salem East)", ta: "ஆத்தூர் (சேலம் கிழக்கு)" },
        { en: "Ayothiyapattinam", ta: "அயோத்தியாப்பட்டினம்" },
        { en: "Dadagapatti", ta: "தடகப்பட்டி" },
        { en: "Edapadi", ta: "எடப்பாடி" },
        { en: "Gangavalli", ta: "கங்கவல்லி" },
        { en: "Jalakandapuram", ta: "ஜலகண்டபுரம்" },
        { en: "Kadaiyampatty", ta: "கடையம்பட்டி" },
        { en: "Magudanchavadi", ta: "மகுடாஞ்சாவடி" },
        { en: "Mallasamuthiram", ta: "மல்லசமுத்திரம்" },
        { en: "Mecheri", ta: "மேச்சேரி" },
        { en: "Mettur", ta: "மேட்டூர்" },
        { en: "Omalur", ta: "ஓமலூர்" },
        { en: "Pethanayakanpalayam", ta: "பேதநாயக்கன்பாளையம்" },
        { en: "Sangagiri", ta: "சங்ககிரி" },
        { en: "Suramangalam", ta: "சுரமங்களம்" },
        { en: "Thalaivasal", ta: "தலைவாசல்" },
        { en: "Thammampatti", ta: "தம்மம்பட்டி" },
        { en: "Tharamangalam", ta: "தாரமங்கலம்" },
        { en: "Vazhapadi", ta: "வாழப்பாடி" },
        { en: "Veerapandi", ta: "வீரப்பாண்டி" },
        { en: "Yercaud", ta: "ஏற்காடு" },
      ]},
      { en: "Namakkal", ta: "நாமக்கல்", offices: [
        { en: "Namakkal Joint I", ta: "நாமக்கல் கூட்டு I" },
        { en: "Namakkal Joint II", ta: "நாமக்கல் கூட்டு II" },
        { en: "Rasipuram", ta: "ராசிபுரம்" },
        { en: "Erumaipatti", ta: "எருமைப்பட்டி" },
        { en: "Kumarapalayam", ta: "குமாரபாளையம்" },
        { en: "Moganur", ta: "மோகனூர்" },
        { en: "Namagiripettai", ta: "நாமகிரிப்பேட்டை" },
        { en: "Pallipalayam", ta: "பள்ளிபாளையம்" },
        { en: "Paramathi", ta: "பரமத்தி" },
        { en: "Puduchathiram (Namakkal)", ta: "புதுசத்திரம் (நாமக்கல்)" },
        { en: "Senthamangalam", ta: "செந்தமங்கலம்" },
        { en: "Thiruchengode", ta: "திருச்செங்கோடு" },
        { en: "Velagoundampatti", ta: "வேலகவுண்டம்பட்டி" },
        { en: "Velur", ta: "வேலூர்" },
      ]},
      { en: "Krishnagiri", ta: "கிருஷ்ணகிரி", offices: [
        { en: "Krishnagiri Joint I", ta: "கிருஷ்ணகிரி கூட்டு I" },
        { en: "Krishnagiri Joint II", ta: "கிருஷ்ணகிரி கூட்டு II" },
        { en: "Bagalur", ta: "பகலூர்" },
        { en: "Bargur", ta: "பர்கூர்" },
        { en: "Hozur", ta: "ஓசூர்" },
        { en: "Kaveripattinam", ta: "காவேரிப்பட்டினம்" },
        { en: "Kelamangalam", ta: "கேளமங்கலம்" },
        { en: "Mathur", ta: "மாத்தூர்" },
        { en: "Oothangarai", ta: "உத்தங்கரை" },
        { en: "Pochampalli", ta: "பொச்சம்பள்ளி" },
        { en: "Rayakottai", ta: "ராயக்கோட்டை" },
        { en: "Soolagiri", ta: "சூளகிரி" },
        { en: "Thenkanikottai", ta: "தென்கனிக்கோட்டை" },
        { en: "Veppannapalli", ta: "வேப்பனப்பள்ளி" },
      ]},
      { en: "Dharmapuri", ta: "தர்மபுரி", offices: [
        { en: "Dharmapuri Joint I", ta: "தர்மபுரி கூட்டு I" },
        { en: "Dharmapuri Joint II", ta: "தர்மபுரி கூட்டு II" },
        { en: "Dharmapuri (West)", ta: "தர்மபுரி (மேற்கு)" },
        { en: "Barur", ta: "பாரூர்" },
        { en: "Harur", ta: "அரூர்" },
        { en: "Kadathur", ta: "கடத்தூர்" },
        { en: "Karimangalam", ta: "கரிமங்கலம்" },
        { en: "Marandahalli", ta: "மரந்தஹள்ளி" },
        { en: "Morapur", ta: "மொரப்பூர்" },
        { en: "Palacode", ta: "பாலக்கோடு" },
        { en: "Papparappatti", ta: "பப்பாரப்பட்டி" },
        { en: "Pappireddypatti", ta: "பாப்பிரெட்டிபட்டி" },
        { en: "Pennagaram", ta: "பென்னாகரம்" },
      ]},
    ],
  },
  {
    en: "Tanjore Zone", ta: "தஞ்சாவூர் மண்டலம்",
    districts: [
      { en: "Thanjavur", ta: "தஞ்சாவூர்", offices: [
        { en: "Thanjavur Joint I", ta: "தஞ்சாவூர் கூட்டு I" },
        { en: "Kumbakonam Joint I", ta: "கும்பகோணம் கூட்டு I" },
        { en: "Ammapettai (Thanjavur)", ta: "அம்மாப்பேட்டை (தஞ்சாவூர்)" },
        { en: "Ayyampettai", ta: "ஐயம்பேட்டை" },
        { en: "Boothalur", ta: "புதலூர்" },
        { en: "Karunthattankudi", ta: "கருந்தட்டான்குடி" },
        { en: "Madukkur", ta: "மடுக்கூர்" },
        { en: "Orathanadu", ta: "ஓரத்தநாடு" },
        { en: "Papanasam", ta: "பாபநாசம்" },
        { en: "Pappanadu", ta: "பப்பநாடு" },
        { en: "Pattukottai Joint I", ta: "பட்டுக்கோட்டை கூட்டு I" },
        { en: "Pattukottai Joint II", ta: "பட்டுக்கோட்டை கூட்டு II" },
        { en: "Peravoorani", ta: "பேராவூரணி" },
        { en: "Subbramaniyapuram", ta: "சுப்ரமணியபுரம்" },
        { en: "Swamimalai", ta: "சுவாமிமலை" },
        { en: "Thakkattur", ta: "தக்கட்டூர்" },
        { en: "Thirukattupalli", ta: "திருக்காட்டுப்பள்ளி" },
        { en: "Thiruppanandhal", ta: "திருப்பனந்தாள்" },
        { en: "Thiruvaiyaru", ta: "திருவையாறு" },
        { en: "Thiruvidaimarudhur", ta: "திருவிடைமருதூர்" },
        { en: "Thiruvonam", ta: "திருவோணம்" },
        { en: "Ullikottai", ta: "உள்ளிக்கோட்டை" },
        { en: "Vallam (Thanjavur)", ta: "வல்லம் (தஞ்சாவூர்)" },
      ]},
      { en: "Tiruvarur", ta: "திருவாரூர்", offices: [
        { en: "Thiruvarur Joint I", ta: "திருவாரூர் கூட்டு I" },
        { en: "Kodavasal", ta: "கோடவாசல்" },
        { en: "Koothanalur", ta: "கூத்தாநல்லூர்" },
        { en: "Mannarkudi", ta: "மன்னார்குடி" },
        { en: "Muthupettai", ta: "முத்துப்பேட்டை" },
        { en: "Nachiyarkovil", ta: "நாச்சியார்கோயில்" },
        { en: "Nannilam", ta: "நன்னிலம்" },
        { en: "Needamangalam", ta: "நீடாமங்கலம்" },
        { en: "Thirukuvalai", ta: "திருக்குவளை" },
        { en: "Thiruthuraipoondi", ta: "திருத்துறைப்பூண்டி" },
        { en: "Valankaiman", ta: "வாலங்கைமான்" },
      ]},
      { en: "Nagapattinam", ta: "நாகப்பட்டினம்", offices: [
        { en: "Nagapatinam Joint I", ta: "நாகப்பட்டினம் கூட்டு I" },
        { en: "Nagoor", ta: "நாகூர்" },
        { en: "Thirupoondi", ta: "திருப்பூண்டி" },
        { en: "Vedharanyam", ta: "வேதாரண்யம்" },
      ]},
      { en: "Mayiladuthurai", ta: "மயிலாடுதுறை", offices: [
        { en: "Mayiladuthurai Joint I", ta: "மயிலாடுதுறை கூட்டு I" },
        { en: "Mayiladuthurai Joint II", ta: "மயிலாடுதுறை கூட்டு II" },
        { en: "Chembanarkovil", ta: "செம்பனார்கோயில்" },
        { en: "Erandampulikadu", ta: "ஏரண்டம்புலிக்காடு" },
        { en: "Keeramangalam", ta: "கீரமங்கலம்" },
        { en: "Kollidam", ta: "கொள்ளிடம்" },
        { en: "Kuthalam", ta: "குத்தாலம்" },
        { en: "Peralam", ta: "பேராளம்" },
        { en: "Seerkazhi", ta: "சீர்காழி" },
        { en: "Tharangampadi", ta: "தரங்கம்பாடி" },
      ]},
    ],
  },
  {
    en: "Trichy Zone", ta: "திருச்சி மண்டலம்",
    districts: [
      { en: "Tiruchirapalli", ta: "திருச்சிராப்பள்ளி", offices: [
        { en: "Trichy Joint I", ta: "திருச்சி கூட்டு I" },
        { en: "Trichi Joint III", ta: "திருச்சி கூட்டு III" },
        { en: "Srirangam", ta: "ஸ்ரீரங்கம்" },
        { en: "Lalkudi", ta: "லால்குடி" },
        { en: "Manaparai", ta: "மணப்பாறை" },
        { en: "Manachanallur", ta: "மணச்சநல்லூர்" },
        { en: "Musiri", ta: "முசிறி" },
        { en: "Thillai Nagar", ta: "தில்லை நகர்" },
        { en: "Thuraiyur", ta: "துறையூர்" },
        { en: "Thiruvarumpur", ta: "திருவெறும்பூர்" },
        { en: "Thuvarankurichi", ta: "துவாரங்குறிச்சி" },
        { en: "Uppiliyapuram", ta: "உப்பிலியாபுரம்" },
        { en: "Urayur", ta: "உறையூர்" },
        { en: "Velayuthampalayam", ta: "வேலாயுதம்பாளையம்" },
        { en: "Velliyanai", ta: "வெள்ளியனை" },
      ]},
      { en: "Karur", ta: "கரூர்", offices: [
        { en: "Karur Joint I", ta: "கரூர் கூட்டு I" },
        { en: "Karur Joint II", ta: "கரூர் கூட்டு II" },
        { en: "Aravakurichi", ta: "அரவக்குறிச்சி" },
        { en: "Chinnadarapuram", ta: "சின்னதாராபுரம்" },
        { en: "Kanakiliyanallur", ta: "கனகிளியநல்லூர்" },
        { en: "Kattuputhur", ta: "காட்டுப்புதூர்" },
        { en: "Krishnarayapuram", ta: "கிருஷ்ணராயபுரம்" },
        { en: "Kulithalai", ta: "குளித்தலை" },
        { en: "Melakarur", ta: "மேலகரூர்" },
        { en: "Nangavaram", ta: "நங்காவரம்" },
        { en: "Tharagampatti", ta: "தாரகம்பட்டி" },
        { en: "Thathaiyangarpettai", ta: "தத்தையங்கார்பேட்டை" },
      ]},
      { en: "Perambalur", ta: "பெரம்பலூர்", offices: [
        { en: "Perambalur Joint I", ta: "பெரம்பலூர் கூட்டு I" },
        { en: "Veppanthattai", ta: "வெப்பந்தட்டை" },
        { en: "Veppur (Perambalur)", ta: "வெப்பூர் (பெரம்பலூர்)" },
        { en: "Kolakkanatham", ta: "கொலக்கநாதம்" },
        { en: "Kolathur", ta: "கோலத்தூர்" },
      ]},
      { en: "Pudukkottai", ta: "புதுக்கோட்டை", offices: [
        { en: "Pudukkottai Joint I", ta: "புதுக்கோட்டை கூட்டு I" },
        { en: "Alangudi", ta: "அலங்குடி" },
        { en: "Annavasal", ta: "அண்ணவாசல்" },
        { en: "Erumbulikurichi", ta: "எரும்புலிக்குறிச்சி" },
        { en: "Iluppur", ta: "இலுப்பூர்" },
        { en: "Kantharvakottai", ta: "கந்தர்வக்கோட்டை" },
        { en: "Karambakudi", ta: "கரம்பக்குடி" },
        { en: "Keelanilai", ta: "கீழநிலை" },
        { en: "Keezhsathanur", ta: "கீழ்சாதனூர்" },
        { en: "Keezhaapazhur", ta: "கீழாப்பழூர்" },
        { en: "Manamelkudi", ta: "மணமேல்குடி" },
        { en: "Perungalur", ta: "பெருங்களூர்" },
        { en: "Pullampadi", ta: "புள்ளம்பாடி" },
        { en: "Tha. Pazhur", ta: "த. பழூர்" },
        { en: "Thirumayam", ta: "திருமயம்" },
        { en: "Vikramangalam", ta: "விக்ரமங்களம்" },
        { en: "Viralimalai", ta: "விரளிமலை" },
      ]},
      { en: "Ariyalur", ta: "அரியலூர்", offices: [
        { en: "Ariyalur Joint I", ta: "அரியலூர் கூட்டு I" },
        { en: "Aandimadam", ta: "ஆண்டிமடம்" },
        { en: "Jayakondam", ta: "ஜெயங்கொண்டம்" },
        { en: "Sendhurai (Ariyalur)", ta: "செந்துறை (அரியலூர்)" },
        { en: "Udayarpalayam", ta: "உதயார்பாளையம்" },
        { en: "Valighandapuram", ta: "வாலிகண்டபுரம்" },
      ]},
    ],
  },
  {
    en: "Thirunelveli Zone", ta: "திருநெல்வேலி மண்டலம்",
    districts: [
      { en: "Tirunelveli", ta: "திருநெல்வேலி", offices: [
        { en: "Tirunelveli Joint I", ta: "திருநெல்வேலி கூட்டு I" },
        { en: "Tirunelveli Joint II", ta: "திருநெல்வேலி கூட்டு II" },
        { en: "Palayankottai Joint I", ta: "பாளையங்கோட்டை கூட்டு I" },
        { en: "Ambasamudhiram", ta: "அம்பாசமுத்திரம்" },
        { en: "Cheranmahadevi Joint I", ta: "சேரன்மகாதேவி கூட்டு I" },
        { en: "Cheranmahadevi Joint II", ta: "சேரன்மகாதேவி கூட்டு II" },
        { en: "Gangaikondan", ta: "கங்கைகொண்டான்" },
        { en: "Kalakkadu", ta: "கல்லக்காடு" },
        { en: "Kallidaikurichi", ta: "கல்லிடைக்குறிச்சி" },
        { en: "Manur", ta: "மானூர்" },
        { en: "Melapapalayam", ta: "மேலபபாளையம்" },
        { en: "Moolakaraipatti", ta: "மூலகரைப்பட்டி" },
        { en: "Mukkoodal", ta: "முக்கூடல்" },
        { en: "Murapanadu", ta: "முரப்பநாடு" },
        { en: "Nanguneri", ta: "நாங்குநேரி" },
        { en: "Panagudi", ta: "பணகுடி" },
        { en: "Pettai", ta: "பேட்டை" },
        { en: "Radhapuram", ta: "ராதாபுரம்" },
        { en: "Thirukurungudi", ta: "திருக்குறுங்குடி" },
        { en: "Valliyur", ta: "வள்ளியூர்" },
        { en: "Veerasigamani", ta: "வீரசிகாமணி" },
        { en: "Vickramasingapuram", ta: "விக்ரமசிங்கபுரம்" },
      ]},
      { en: "Tenkasi", ta: "தென்காசி", offices: [
        { en: "Tenkasi Joint I", ta: "தென்காசி கூட்டு I" },
        { en: "Tenkasi Joint II", ta: "தென்காசி கூட்டு II" },
        { en: "Alangulam", ta: "ஆலங்குளம்" },
        { en: "Burkitmanagaram", ta: "புர்கிட்மானகரம்" },
        { en: "Idaikkal", ta: "இடைக்கல்" },
        { en: "Idalagudi", ta: "இடலகுடி" },
        { en: "Kadambur", ta: "கடம்பூர்" },
        { en: "Kadayam", ta: "கடயம்" },
        { en: "Kadayanallur", ta: "கடையநல்லூர்" },
        { en: "Karivalamvandanallur", ta: "கரிவலம்வந்தநல்லூர்" },
        { en: "Keezhur", ta: "கீழூர்" },
        { en: "Kommadikottai", ta: "கொம்மடிக்கோட்டை" },
        { en: "Melaneelithanallur", ta: "மேலநீலித்தநல்லூர்" },
        { en: "Panpozhi", ta: "பான்பொழி" },
        { en: "Pavoorchathram", ta: "பவூர்சத்திரம்" },
        { en: "Puliyangudi", ta: "புளியங்குடி" },
        { en: "Sankaranainarkoil", ta: "சங்கரநைனார்கோயில்" },
        { en: "Senkottai", ta: "செங்கோட்டை" },
        { en: "Sivagiri (Tenkasi)", ta: "சிவகிரி (தென்காசி)" },
        { en: "Surandai", ta: "சுரண்டை" },
        { en: "Uthumalai", ta: "உத்துமலை" },
        { en: "Vadakkuveeravanallur", ta: "வடக்குவீரவநல்லூர்" },
        { en: "Vasudevanallur", ta: "வாசுதேவநல்லூர்" },
      ]},
      { en: "Thoothukudi", ta: "தூத்துக்குடி", offices: [
        { en: "Tuticorin Joint I", ta: "தூத்துக்குடி கூட்டு I" },
        { en: "Tuticorin Joint II", ta: "தூத்துக்குடி கூட்டு II" },
        { en: "Eral", ta: "ஏரல்" },
        { en: "Ettayapuram", ta: "எட்டயபுரம்" },
        { en: "Kalugumalai", ta: "கழுகுமலை" },
        { en: "Kayalpattinam", ta: "காயல்பட்டினம்" },
        { en: "Kayathar", ta: "காயத்தார்" },
        { en: "Kovilpatti", ta: "கோவில்பட்டி" },
        { en: "Melur (Tuticorin)", ta: "மேலூர் (தூத்துக்குடி)" },
        { en: "Nazareth", ta: "நாசரேத்" },
        { en: "Ottapidaram", ta: "ஒட்டப்பிடாரம்" },
        { en: "Perungulam", ta: "பெருங்குளம்" },
        { en: "Pudukkottai (Tuticorin)", ta: "புதுக்கோட்டை (தூத்துக்குடி)" },
        { en: "Pudur", ta: "புதூர்" },
        { en: "Sathankulam", ta: "சாத்தான்குளம்" },
        { en: "Srivaikundam", ta: "ஸ்ரீவைகுண்டம்" },
        { en: "Thisaiyanvilai", ta: "திசையன்விளை" },
        { en: "Tiruchendur", ta: "திருச்செந்தூர்" },
        { en: "Udankudi", ta: "உடன்குடி" },
        { en: "Vilathikulam", ta: "விளாத்திக்குளம்" },
      ]},
      { en: "Kanyakumari", ta: "கன்னியாகுமரி", offices: [
        { en: "Kanyakumari Joint I", ta: "கன்னியாகுமரி கூட்டு I" },
        { en: "Marthandam Joint I", ta: "மார்த்தாண்டம் கூட்டு I" },
        { en: "Marthandam Joint II", ta: "மார்த்தாண்டம் கூட்டு II" },
        { en: "Arumanai", ta: "அருமணை" },
        { en: "Boothapandi", ta: "பூதப்பாண்டி" },
        { en: "Eranial", ta: "ஏரணியல்" },
        { en: "Karungal", ta: "கருங்கல்" },
        { en: "Kollankodu", ta: "கொள்ளங்கோடு" },
        { en: "Kottaram", ta: "கோட்டாரம்" },
        { en: "Kulatchal", ta: "குலச்சல்" },
        { en: "Manavalakurichi", ta: "மணவாளக்குறிச்சி" },
        { en: "Munchirai", ta: "முஞ்சிறை" },
        { en: "Palliyadi", ta: "பல்லியாடி" },
        { en: "Palugal", ta: "பளுகல்" },
        { en: "Rajackamangalam", ta: "ராஜாக்கமங்களம்" },
        { en: "Thackalai", ta: "தக்களை" },
        { en: "Thiruvattar", ta: "திருவாட்டார்" },
        { en: "Thovalai", ta: "தோவளை" },
        { en: "Vadaseri", ta: "வடசேரி" },
        { en: "Verkilambi", ta: "வேற்கிலம்பி" },
      ]},
    ],
  },
  {
    en: "Vellore Zone", ta: "வேலூர் மண்டலம்",
    districts: [
      { en: "Vellore", ta: "வேலூர்", offices: [
        { en: "Vellore Joint I", ta: "வேலூர் கூட்டு I" },
        { en: "Katpadi", ta: "காட்பாடி" },
        { en: "Kaniyampadi", ta: "கனியம்பாடி" },
        { en: "Kudiyatham", ta: "குடியாத்தம்" },
        { en: "Odugathur", ta: "ஒடுகத்தூர்" },
        { en: "Pallikonda", ta: "பல்லிக்கொண்டா" },
        { en: "Pernampattu", ta: "பேர்நாம்பட்டு" },
      ]},
      { en: "Ranipet", ta: "ராணிப்பேட்டை", offices: [
        { en: "Ranipet Joint I", ta: "ராணிப்பேட்டை கூட்டு I" },
        { en: "Arakkonam", ta: "அரக்கோணம்" },
        { en: "Arcot", ta: "ஆற்காடு" },
        { en: "Kalavai", ta: "களவை" },
        { en: "Kaveripakkam", ta: "காவேரிப்பாக்கம்" },
        { en: "Nemili", ta: "நெமிலி" },
        { en: "Sholingar", ta: "சோழிங்கர்" },
        { en: "Walaja", ta: "வாலாஜா" },
      ]},
      { en: "Tirupathur", ta: "திருப்பத்தூர்", offices: [
        { en: "Thirupathur Joint I", ta: "திருப்பத்தூர் கூட்டு I" },
        { en: "Thirupathur Joint II", ta: "திருப்பத்தூர் கூட்டு II" },
        { en: "Ambur", ta: "ஆம்பூர்" },
        { en: "Jolarpettai", ta: "ஜோலார்பேட்டை" },
        { en: "Natrampalli", ta: "நாட்ரம்பள்ளி" },
        { en: "Vaniyampadi", ta: "வாணியம்பாடி" },
      ]},
      { en: "Tiruvannamalai", ta: "திருவண்ணாமலை", offices: [
        { en: "Thiruvannamalai Joint I", ta: "திருவண்ணாமலை கூட்டு I" },
        { en: "Thiruvannamalai Joint II", ta: "திருவண்ணாமலை கூட்டு II" },
        { en: "Cheyyar Joint I", ta: "செய்யாறு கூட்டு I" },
        { en: "Cheyyar Joint II", ta: "செய்யாறு கூட்டு II" },
        { en: "Arani (Cheyyar)", ta: "ஆரணி (செய்யாறு)" },
        { en: "Chengam", ta: "செங்கம்" },
        { en: "Chetput", ta: "சேட்பேட்டை" },
        { en: "Dusi", ta: "டூசி" },
        { en: "Kadaladi (Thiruvannamalai)", ta: "கடலாடி (திருவண்ணாமலை)" },
        { en: "Kalampur", ta: "களம்பூர்" },
        { en: "Kalasapakkam", ta: "களசபாக்கம்" },
        { en: "Kannamangalam", ta: "கண்ணமங்கலம்" },
        { en: "Keezh Vazhi ThunaiyanKuppam", ta: "கீழ் வழி துணையன்குப்பம்" },
        { en: "Kilkodungalur", ta: "கீழ்கொடுங்களூர்" },
        { en: "Kilpennathur", ta: "கீழ்பெண்ணாத்தூர்" },
        { en: "Mangalam", ta: "மங்களம்" },
        { en: "Peranamallur", ta: "பெரநமல்லூர்" },
        { en: "Polur", ta: "போளூர்" },
        { en: "Thaanipadi", ta: "தாணிப்பாடி" },
        { en: "Thandarampattu", ta: "தண்டராம்பட்டு" },
        { en: "Thellar", ta: "தெல்லார்" },
        { en: "Vandavasi", ta: "வந்தவாசி" },
        { en: "Vembakkam", ta: "வேம்பாக்கம்" },
        { en: "Vettavalam", ta: "வேட்டவலம்" },
      ]},
    ],
  },
];
