// Tamil Nadu Legislative Assembly constituencies grouped by district.
// 234 constituencies across 38 districts. Bilingual labels (en / ta).
// Source: public ECI / TN Election Commission listings.

export interface AssemblyConstituency {
  name: string;
  nameTa: string;
}

export const TN_ASSEMBLY_CONSTITUENCIES: Record<string, AssemblyConstituency[]> = {
  "Ariyalur": [
    { name: "Andimadam", nameTa: "அண்டிமடம்" },
    { name: "Jayankondam", nameTa: "ஜெயங்கொண்டம்" },
    { name: "Ariyalur", nameTa: "அரியலூர்" },
  ],
  "Chengalpattu": [
    { name: "Sholinganallur", nameTa: "சோழிங்கநல்லூர்" },
    { name: "Pallavaram", nameTa: "பல்லாவரம்" },
    { name: "Tambaram", nameTa: "தாம்பரம்" },
    { name: "Chengalpattu", nameTa: "செங்கல்பட்டு" },
    { name: "Thiruporur", nameTa: "திருப்போரூர்" },
    { name: "Cheyyur", nameTa: "செய்யூர்" },
            { name: "Madurantakam", nameTa: "மதுராந்தகம்" },
  ],
  "Chennai": [
    { name: "Dr. Radhakrishnan Nagar", nameTa: "டாக்டர் ராதாகிருஷ்ணன் நகர்" },
    { name: "Perambur", nameTa: "பெரம்பூர்" },
    { name: "Kolathur", nameTa: "கொளத்தூர்" },
    { name: "Villivakkam", nameTa: "விளிவாக்கம்" },
    { name: "Thiru-Vi-Ka Nagar", nameTa: "திரு-வி-க நகர்" },
    { name: "Egmore", nameTa: "எழும்பூர்" },
    { name: "Royapuram", nameTa: "ராயபுரம்" },
    { name: "Harbour", nameTa: "துறைமுகம்" },
    { name: "Chepauk-Triplicane", nameTa: "செப்பாக்கம்-திருவல்லிக்கேணி" },
    { name: "Thousand Lights", nameTa: "ஆயிரம் விளக்கு" },
    { name: "Anna Nagar", nameTa: "அண்ணா நகர்" },
    { name: "Virugampakkam", nameTa: "விருகம்பாக்கம்" },
    { name: "Saidapet", nameTa: "சைதாப்பேட்டை" },
    { name: "Thiyagaraya Nagar", nameTa: "தியாகராய நகர்" },
    { name: "Mylapore", nameTa: "மயிலாப்பூர்" },
    { name: "Velachery", nameTa: "வேளச்சேரி" },
  ],
  "Coimbatore": [
    { name: "Mettupalayam", nameTa: "மேட்டுப்பாளையம்" },
    { name: "Sulur", nameTa: "சூலூர்" },
    { name: "Kavundampalayam", nameTa: "கவுண்டம்பாளையம்" },
    { name: "Coimbatore North", nameTa: "கோயம்புத்தூர் வடக்கு" },
    { name: "Thondamuthur", nameTa: "தொண்டாமுத்தூர்" },
    { name: "Coimbatore South", nameTa: "கோயம்புத்தூர் தெற்கு" },
    { name: "Singanallur", nameTa: "சிங்காநல்லூர்" },
    { name: "Kinathukadavu", nameTa: "கிணத்துக்கடவு" },
    { name: "Pollachi", nameTa: "பொள்ளாச்சி" },
    { name: "Valparai", nameTa: "வால்பாறை" },
  ],
  "Cuddalore": [
    { name: "Tittakudi", nameTa: "திட்டக்குடி" },
    { name: "Vriddhachalam", nameTa: "விருத்தாசலம்" },
    { name: "Neyveli", nameTa: "நெய்வேலி" },
    { name: "Panruti", nameTa: "பண்ருட்டி" },
    { name: "Cuddalore", nameTa: "கடலூர்" },
    { name: "Kurinjipadi", nameTa: "குறிஞ்சிப்பாடி" },
    { name: "Bhuvanagiri", nameTa: "புவனகிரி" },
    { name: "Chidambaram", nameTa: "சிதம்பரம்" },
            { name: "Kattumannarkoil", nameTa: "காட்டுமன்னார்கோயில்" },
  ],
  "Dharmapuri": [
    { name: "Palacode", nameTa: "பாலக்கோடு" },
    { name: "Pennagaram", nameTa: "பென்னாகரம்" },
    { name: "Dharmapuri", nameTa: "தர்மபுரி" },
    { name: "Pappireddippatti", nameTa: "பாப்பிரெட்டிப்பட்டி" },
            { name: "Harur", nameTa: "ஹரூர்" },
  ],
  "Dindigul": [
    { name: "Palani", nameTa: "பழனி" },
    { name: "Oddanchatram", nameTa: "ஒட்டன்சத்திரம்" },
    { name: "Athoor", nameTa: "ஆத்தூர்" },
    { name: "Nilakottai", nameTa: "நிலக்கோட்டை" },
    { name: "Natham", nameTa: "நத்தம்" },
    { name: "Dindigul", nameTa: "திண்டுக்கல்" },
            { name: "Vedasandur", nameTa: "வேடசந்தூர்" },
  ],
  "Erode": [
    { name: "Erode East", nameTa: "ஈரோடு கிழக்கு" },
    { name: "Erode West", nameTa: "ஈரோடு மேற்கு" },
    { name: "Modakkurichi", nameTa: "மொடக்குறிச்சி" },
    { name: "Perundurai", nameTa: "பெருந்துறை" },
    { name: "Bhavani", nameTa: "பவானி" },
    { name: "Anthiyur", nameTa: "அந்தியூர்" },
    { name: "Gobichettipalayam", nameTa: "கோபிசெட்டிபாளையம்" },
            { name: "Bhavanisagar", nameTa: "பவானிசாகர்" },
  ],
  "Kallakurichi": [
    { name: "Kallakurichi", nameTa: "கள்ளக்குறிச்சி" },
    { name: "Sankarapuram", nameTa: "சங்கராபுரம்" },
    { name: "Chinnasalem", nameTa: "சின்னசேலம்" },
            { name: "Rishivandiyam", nameTa: "ரிஷிவந்தியம்" },
  ],
  "Kancheepuram": [
    { name: "Sriperumbudur", nameTa: "ஸ்ரீபெரும்புதூர்" },
    { name: "Kancheepuram", nameTa: "காஞ்சிபுரம்" },
            { name: "Uthiramerur", nameTa: "உத்திரமேரூர்" },
  ],
  "Kanyakumari": [
    { name: "Kanniyakumari", nameTa: "கன்னியாகுமரி" },
    { name: "Nagercoil", nameTa: "நாகர்கோவில்" },
    { name: "Colachel", nameTa: "கொளச்சல்" },
    { name: "Padmanabhapuram", nameTa: "பத்மநாபபுரம்" },
    { name: "Vilavancode", nameTa: "விளவங்கோடு" },
            { name: "Killiyoor", nameTa: "கிள்ளியூர்" },
  ],
  "Karur": [
    { name: "Aravakurichi", nameTa: "அரவக்குறிச்சி" },
    { name: "Karur", nameTa: "கரூர்" },
    { name: "Krishnarayapuram", nameTa: "கிருஷ்ணராயபுரம்" },
            { name: "Kulithalai", nameTa: "குளித்தலை" },
  ],
  "Krishnagiri": [
    { name: "Uthangarai", nameTa: "உத்தங்கரை" },
    { name: "Bargur", nameTa: "பர்கூர்" },
    { name: "Krishnagiri", nameTa: "கிருஷ்ணகிரி" },
    { name: "Veppanahalli", nameTa: "வேப்பனஹள்ளி" },
    { name: "Hosur", nameTa: "ஓசூர்" },
            { name: "Thalli", nameTa: "தளி" },
  ],
  "Madurai": [
    { name: "Melur", nameTa: "மேலூர்" },
    { name: "Madurai East", nameTa: "மதுரை கிழக்கு" },
    { name: "Sholavandan", nameTa: "சோழவந்தான்" },
    { name: "Madurai North", nameTa: "மதுரை வடக்கு" },
    { name: "Madurai South", nameTa: "மதுரை தெற்கு" },
    { name: "Madurai Central", nameTa: "மதுரை மத்திய" },
    { name: "Madurai West", nameTa: "மதுரை மேற்கு" },
    { name: "Thiruparankundram", nameTa: "திருப்பரங்குன்றம்" },
    { name: "Thirumangalam", nameTa: "திருமங்கலம்" },
            { name: "Usilampatti", nameTa: "உசிலம்பட்டி" },
  ],
  "Mayiladuthurai": [
    { name: "Sirkazhi", nameTa: "சீர்காழி" },
    { name: "Mayiladuthurai", nameTa: "மயிலாடுதுறை" },
            { name: "Poompuhar", nameTa: "பூம்புகார்" },
  ],
  "Nagapattinam": [
    { name: "Nagapattinam", nameTa: "நாகப்பட்டினம்" },
    { name: "Kilvelur", nameTa: "கீழ்வேளூர்" },
            { name: "Vedaranyam", nameTa: "வேதாரண்யம்" },
  ],
  "Namakkal": [
    { name: "Rasipuram", nameTa: "ராசிபுரம்" },
    { name: "Senthamangalam", nameTa: "செந்தமங்கலம்" },
    { name: "Namakkal", nameTa: "நாமக்கல்" },
    { name: "Paramathi-Velur", nameTa: "பரமத்தி-வேலூர்" },
            { name: "Tiruchengode", nameTa: "திருச்செங்கோடு" },
  ],
  "Nilgiris": [
    { name: "Udhagamandalam", nameTa: "உதகமண்டலம்" },
    { name: "Gudalur", nameTa: "கூடலூர்" },
            { name: "Coonoor", nameTa: "குன்னூர்" },
  ],
  "Perambalur": [
    { name: "Perambalur", nameTa: "பெரம்பலூர்" },
            { name: "Kunnam", nameTa: "குன்னம்" },
  ],
  "Pudukkottai": [
    { name: "Gandharvakottai", nameTa: "கந்தர்வகோட்டை" },
    { name: "Viralimalai", nameTa: "விராலிமலை" },
    { name: "Pudukkottai", nameTa: "புதுக்கோட்டை" },
    { name: "Thirumayam", nameTa: "திருமயம்" },
            { name: "Alangudi", nameTa: "ஆலங்குடி" },
            { name: "Aranthangi", nameTa: "அறந்தாங்கி" },
  ],
  "Ramanathapuram": [
    { name: "Paramakudi", nameTa: "பரமக்குடி" },
    { name: "Tiruvadanai", nameTa: "திருவாடானை" },
    { name: "Ramanathapuram", nameTa: "இராமநாதபுரம்" },
            { name: "Mudhukulathur", nameTa: "முதுகுளத்தூர்" },
  ],
  "Ranipet": [
    { name: "Arakkonam", nameTa: "அரக்கோணம்" },
    { name: "Sholingur", nameTa: "சோளிங்கர்" },
    { name: "Ranipet", nameTa: "ராணிப்பேட்டை" },
            { name: "Arcot", nameTa: "ஆற்காடு" },
  ],
  "Salem": [
    { name: "Gangavalli", nameTa: "கங்கவல்லி" },
    { name: "Attur", nameTa: "ஆத்தூர்" },
    { name: "Yercaud", nameTa: "ஏற்காடு" },
    { name: "Omalur", nameTa: "ஓமலூர்" },
    { name: "Mettur", nameTa: "மேட்டூர்" },
    { name: "Edappadi", nameTa: "எடப்பாடி" },
    { name: "Sankari", nameTa: "சங்ககிரி" },
    { name: "Salem West", nameTa: "சேலம் மேற்கு" },
    { name: "Salem North", nameTa: "சேலம் வடக்கு" },
    { name: "Salem South", nameTa: "சேலம் தெற்கு" },
            { name: "Veerapandi", nameTa: "வீரபாண்டி" },
  ],
  "Sivaganga": [
    { name: "Karaikudi", nameTa: "காரைக்குடி" },
    { name: "Tiruppattur", nameTa: "திருப்பத்தூர்" },
    { name: "Sivaganga", nameTa: "சிவகங்கை" },
            { name: "Manamadurai", nameTa: "மானாமதுரை" },
  ],
  "Tenkasi": [
    { name: "Sankarankovil", nameTa: "சங்கரன்கோவில்" },
    { name: "Vasudevanallur", nameTa: "வாசுதேவநல்லூர்" },
    { name: "Kadayanallur", nameTa: "கடையநல்லூர்" },
    { name: "Tenkasi", nameTa: "தென்காசி" },
            { name: "Alangulam", nameTa: "ஆலங்குளம்" },
  ],
  "Thanjavur": [
    { name: "Thiruvidaimarudur", nameTa: "திருவிடைமருதூர்" },
    { name: "Kumbakonam", nameTa: "கும்பகோணம்" },
    { name: "Papanasam", nameTa: "பாபநாசம்" },
    { name: "Thiruvaiyaru", nameTa: "திருவையாறு" },
    { name: "Thanjavur", nameTa: "தஞ்சாவூர்" },
    { name: "Orathanadu", nameTa: "ஓரத்தநாடு" },
    { name: "Pattukkottai", nameTa: "பட்டுக்கோட்டை" },
            { name: "Peravurani", nameTa: "பேராவூரணி" },
  ],
  "Theni": [
    { name: "Andipatti", nameTa: "ஆண்டிப்பட்டி" },
    { name: "Periyakulam", nameTa: "பெரியகுளம்" },
    { name: "Bodinayakanur", nameTa: "போடிநாயக்கனூர்" },
            { name: "Cumbum", nameTa: "கம்பம்" },
  ],
  "Thoothukudi": [
    { name: "Vilathikulam", nameTa: "விளாத்திகுளம்" },
    { name: "Thoothukkudi", nameTa: "தூத்துக்குடி" },
    { name: "Tiruchendur", nameTa: "திருச்செந்தூர்" },
    { name: "Srivaikuntam", nameTa: "ஸ்ரீவைகுண்டம்" },
    { name: "Ottapidaram", nameTa: "ஓட்டப்பிடாரம்" },
            { name: "Kovilpatti", nameTa: "கோவில்பட்டி" },
  ],
  "Tiruchirappalli": [
    { name: "Manapparai", nameTa: "மணப்பாறை" },
    { name: "Srirangam", nameTa: "ஸ்ரீரங்கம்" },
    { name: "Tiruchirappalli West", nameTa: "திருச்சிராப்பள்ளி மேற்கு" },
    { name: "Tiruchirappalli East", nameTa: "திருச்சிராப்பள்ளி கிழக்கு" },
    { name: "Thiruverumbur", nameTa: "திருவெறும்பூர்" },
    { name: "Lalgudi", nameTa: "லால்குடி" },
    { name: "Manachanallur", nameTa: "மணச்சநல்லூர்" },
    { name: "Musiri", nameTa: "முசிறி" },
            { name: "Thuraiyur", nameTa: "துறையூர்" },
  ],
  "Tirunelveli": [
    { name: "Tirunelveli", nameTa: "திருநெல்வேலி" },
    { name: "Ambasamudram", nameTa: "அம்பாசமுத்திரம்" },
    { name: "Palayamkottai", nameTa: "பாளையங்கோட்டை" },
    { name: "Nanguneri", nameTa: "நாங்குனேரி" },
    { name: "Radhapuram", nameTa: "ராதாபுரம்" },
  ],
  "Tirupathur": [
    { name: "Vaniyambadi", nameTa: "வாணியம்பாடி" },
    { name: "Ambur", nameTa: "ஆம்பூர்" },
    { name: "Jolarpet", nameTa: "ஜோலார்பேட்டை" },
            { name: "Tirupattur", nameTa: "திருப்பத்தூர்" },
  ],
  "Tiruppur": [
    { name: "Dharapuram", nameTa: "தாராபுரம்" },
    { name: "Kangayam", nameTa: "காங்கேயம்" },
    { name: "Avinashi", nameTa: "அவிநாசி" },
    { name: "Tiruppur North", nameTa: "திருப்பூர் வடக்கு" },
    { name: "Tiruppur South", nameTa: "திருப்பூர் தெற்கு" },
    { name: "Palladam", nameTa: "பல்லடம்" },
            { name: "Udumalaipettai", nameTa: "உடுமலைப்பேட்டை" },
            { name: "Madathukulam", nameTa: "மடத்துக்குளம்" },
  ],
  "Tiruvallur": [
    { name: "Gummidipoondi", nameTa: "கும்மிடிப்பூண்டி" },
    { name: "Ponneri", nameTa: "பொன்னேரி" },
    { name: "Tiruttani", nameTa: "திருத்தணி" },
    { name: "Thiruvallur", nameTa: "திருவள்ளூர்" },
    { name: "Poonamallee", nameTa: "பூவிருந்தவல்லி" },
    { name: "Avadi", nameTa: "ஆவடி" },
    { name: "Maduravoyal", nameTa: "மதுரவாயல்" },
    { name: "Ambattur", nameTa: "அம்பத்தூர்" },
    { name: "Madhavaram", nameTa: "மாதவரம்" },
            { name: "Thiruvottiyur", nameTa: "திருவொற்றியூர்" },
  ],
  "Tiruvannamalai": [
    { name: "Chengam", nameTa: "செங்கம்" },
    { name: "Tiruvannamalai", nameTa: "திருவண்ணாமலை" },
    { name: "Kilpennathur", nameTa: "கீழ்பென்னாத்தூர்" },
    { name: "Kalasapakkam", nameTa: "களசபாக்கம்" },
    { name: "Polur", nameTa: "போளூர்" },
    { name: "Arani", nameTa: "ஆரணி" },
    { name: "Cheyyar", nameTa: "செய்யாறு" },
            { name: "Vandavasi", nameTa: "வந்தவாசி" },
  ],
  "Tiruvarur": [
    { name: "Thiruthuraipoondi", nameTa: "திருத்துறைப்பூண்டி" },
    { name: "Mannargudi", nameTa: "மன்னார்குடி" },
    { name: "Thiruvarur", nameTa: "திருவாரூர்" },
            { name: "Nannilam", nameTa: "நன்னிலம்" },
  ],
  "Vellore": [
    { name: "Katpadi", nameTa: "காட்பாடி" },
    { name: "Vellore", nameTa: "வேலூர்" },
    { name: "Anaikattu", nameTa: "ஆனைக்கட்டு" },
            { name: "Kilvaithinankuppam", nameTa: "கீழ்வைதிநாங்குப்பம்" },
            { name: "Gudiyatham", nameTa: "குடியாத்தம்" },
  ],
  "Villupuram": [
    { name: "Gingee", nameTa: "செஞ்சி" },
    { name: "Mailam", nameTa: "மயிலம்" },
    { name: "Tindivanam", nameTa: "திண்டிவனம்" },
    { name: "Vanur", nameTa: "வாணூர்" },
    { name: "Villupuram", nameTa: "விழுப்புரம்" },
    { name: "Vikravandi", nameTa: "விக்கிரவாண்டி" },
            { name: "Tirukkoyilur", nameTa: "திருக்கோயிலூர்" },
  ],
  "Virudhunagar": [
    { name: "Rajapalayam", nameTa: "ராஜபாளையம்" },
    { name: "Srivilliputhur", nameTa: "சீவகாசி" },
    { name: "Sattur", nameTa: "சாத்தூர்" },
    { name: "Sivakasi", nameTa: "சிவகாசி" },
    { name: "Virudhunagar", nameTa: "விருதுநகர்" },
            { name: "Aruppukkottai", nameTa: "அருப்புக்கோட்டை" },
            { name: "Tiruchuli", nameTa: "திருச்சுழி" },
  ],
};

export function getConstituenciesForDistrict(district: string): AssemblyConstituency[] {
  return TN_ASSEMBLY_CONSTITUENCIES[district] ?? [];
}
