kind = "web"
previewPath = "/"
title = "Logesh Connect"
version = "1.0.0"
id = "artifacts/nirmal-connect"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 8081

[services.development]
run = "pnpm --filter @workspace/logesh-connect run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/logesh-connect", "run", "build" ]
publicDir = "artifacts/logesh-connect/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "8081"
BASE_PATH = "/"
